<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copyFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required sourceDirectory</value>
    <value>[i] field:0:required targetDirectory</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcg
c3RyRmlsZW5hbWUgPSAiIjsKU3RyaW5nIHN0clNvdXJjZURpcmVjdG9yeSA9IG51bGw7ClN0cmlu
ZyBzdHJUYXJnZXREaXJlY3RvcnkgPSBudWxsOwoKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJmaWxl
bmFtZSIpKQp7CiAgc3RyRmlsZW5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgp
Owp9CmVsc2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJDb3B5IEZhaWxlZDogRmls
ZW5hbWUgaXMgbnVsbCEiKTsKfQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoInNvdXJjZURpcmVjdG9y
eSIpKQp7CiAgc3RyU291cmNlRGlyZWN0b3J5ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFs
dWUoKTsKfQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoInRhcmdldERpcmVjdG9yeSIpKQp7CiAgc3Ry
VGFyZ2V0RGlyZWN0b3J5ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQoKLy8g
KioqIENoZWNrIGlmIHBhdGhzIGFyZSBvbiB0aGUgYWxsb3dlZCBsaXN0ICoqKgpTdHJpbmcgc3Ry
U291cmNlRnVsbFBhdGggPSBzdHJTb3VyY2VEaXJlY3RvcnkgKyBTeXN0ZW0uZ2V0UHJvcGVydHko
ImZpbGUuc2VwYXJhdG9yIikgKyBzdHJGaWxlbmFtZTsKU3RyaW5nIHN0clRhcmdldEZ1bGxQYXRo
ID0gc3RyVGFyZ2V0RGlyZWN0b3J5ICsgU3lzdGVtLmdldFByb3BlcnR5KCJmaWxlLnNlcGFyYXRv
ciIpICsgc3RyRmlsZW5hbWU7CnRyeQp7CiAgaWYgKCFjaGVja1BhdGhWYWxpZGl0eShzdHJTb3Vy
Y2VGdWxsUGF0aCwgInJlYWQiKSkKICB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
U3BlY2lmaWVkIHBhdGggaXMgbm90IG9uIHRoZSByZWFkIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNV
dGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlISIpOwogIH0KICBpZiAoIWNoZWNrUGF0aFZhbGlk
aXR5KHN0clRhcmdldEZ1bGxQYXRoLCAid3JpdGUiKSkKICB7CiAgICB0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbigiU3BlY2lmaWVkIHBhdGggaXMgbm90IG9uIHRoZSB3cml0ZSBhbGxvd2VkIGxp
c3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsKICB9Cn0KY2F0Y2gg
KEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdl
KCkpOwp9Ci8vICoqKiBFbmQgY2hlY2sgKioqCgppZiAoc3RyU291cmNlRGlyZWN0b3J5ICE9IHN0
clRhcmdldERpcmVjdG9yeSkKewogIEZpbGVSZWFkZXIgZnJTb3VyY2VGaWxlID0gbnVsbDsKICBG
aWxlV3JpdGVyIGZ3VGFyZ2V0RmlsZSA9IG51bGw7CiAgRmlsZSBzb3VyY2VGaWxlID0gbnVsbDsK
ICBGaWxlIHRhcmdldEZpbGUgPSBudWxsOwoKICB0cnkKICB7CgogICAgc291cmNlRmlsZSA9IG5l
dyBGaWxlKHN0clNvdXJjZURpcmVjdG9yeSwgc3RyRmlsZW5hbWUpOwogICAgdGFyZ2V0RmlsZSA9
IG5ldyBGaWxlKHN0clRhcmdldERpcmVjdG9yeSwgc3RyRmlsZW5hbWUpOwoKICAgIGlmICghc291
cmNlRmlsZS5leGlzdHMoKSB8fCBzb3VyY2VGaWxlLmlzRGlyZWN0b3J5KCkpCiAgICB7CiAgICAg
IHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJNT1ZFIEVSUk9SOiBTb3VyY2UgZmlsZSBub3Qg
Zm91bmQgKCIgKyBzb3VyY2VGaWxlLmdldEFic29sdXRlUGF0aCgpICsgIikiKTsKICAgIH0KCiAg
ICBmclNvdXJjZUZpbGUgPSBuZXcgRmlsZVJlYWRlcihzb3VyY2VGaWxlKTsKICAgIGZ3VGFyZ2V0
RmlsZSA9IG5ldyBGaWxlV3JpdGVyKHRhcmdldEZpbGUpOwoKICAgIGludCBjOwogICAgd2hpbGUg
KChjID0gZnJTb3VyY2VGaWxlLnJlYWQoKSkgIT0gLTEpCiAgICB7CiAgICAgIGZ3VGFyZ2V0Rmls
ZS53cml0ZShjKTsKICAgIH0KCiAgICBpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigibWVzc2FnZSIs
ICJDb3BpZWQ6ICIgKyBzb3VyY2VGaWxlLmdldEFic29sdXRlUGF0aCgpICsgIiB0byAiICsgc3Ry
VGFyZ2V0RGlyZWN0b3J5KTsKCiAgfQogIGNhdGNoIChFeGNlcHRpb24gZSkKICB7CiAgICB0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7CiAgfQogIGZpbmFsbHkKICB7
CiAgICB0cnkKICAgIHsKICAgICAgZnJTb3VyY2VGaWxlLmNsb3NlKCk7CiAgICAgIGZ3VGFyZ2V0
RmlsZS5jbG9zZSgpOwogICAgfQogICAgY2F0Y2ggKEV4Y2VwdGlvbiBlKQogICAgewogICAgfQog
ICAgc291cmNlRmlsZSA9IG51bGw7CiAgICB0YXJnZXRGaWxlID0gbnVsbDsKICB9Cn0KCmlkY1Bp
cGVsaW5lLmRlc3Ryb3koKTsK</value>
</Values>
