<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertPackedDecimalToString</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required bytes</value>
    <value>[o] field:0:required integer</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpieXRlIHBhY2tlZEJ5dGVz
W10gPSBudWxsOwppbnQgYW5zd2VyID0gMDsKCmlmIChpZGMuZmlyc3QoImJ5dGVzIikpCnsKICBw
YWNrZWRCeXRlcyA9IChieXRlW10pIGlkYy5nZXRWYWx1ZSgpOwp9CmlmIChwYWNrZWRCeXRlcyAh
PSBudWxsKQp7CiAgaWYgKCEocGFja2VkQnl0ZXMgaW5zdGFuY2VvZiBieXRlW10pKQogIHsKICAg
IGlkYy5kZXN0cm95KCk7IC8vIGVycm9yIGNhc2UKICB9CiAgZWxzZQogIHsKICAgIC8vIFBhY2tl
ZCBEZWNpbWFsIGludG8gYW4gaW50CiAgICBpbnQgaTAgPSAoaW50KSBwYWNrZWRCeXRlc1twYWNr
ZWRCeXRlcy5sZW5ndGggLSAxXSA+Pj4gNDsKICAgIGludCBpMSA9IChpbnQpIHBhY2tlZEJ5dGVz
W3BhY2tlZEJ5dGVzLmxlbmd0aCAtIDFdICYgKDE1KTsKICAgIGJvb2xlYW4gcGx1cyA9IChpMSA9
PSAxMikgfCAoaTEgPT0gMTUpOyAvLyBkZXRlcm1pbmUKICAgIC8vIHNpZ24gZGlnaXQKICAgIGFu
c3dlciA9IGkwOwogICAgaW50IGRpZ2l0ID0gMTA7IC8vIFBvd2VyIG9mIDEwIC0gZWFjaCBkaWdp
dCdzCiAgICAvLyBwbGFjZSB2YWx1ZQoKICAgIGZvciAoaW50IGkgPSBwYWNrZWRCeXRlcy5sZW5n
dGggLSAyOyBpID4gLTE7IGktLSkKICAgIHsKICAgICAgYnl0ZSB4ID0gcGFja2VkQnl0ZXNbaV07
CiAgICAgIGkwID0gKGludCkgeCA+Pj4gNDsgLy8gc2hpZnQgcmlnaHQgNCB0byBnZXQgaGlnaAog
ICAgICAvLyBvcmRlciBkaWdpdAogICAgICBpMSA9IChpbnQpIHggJiAoMTUpOyAvLyBBTkQgd2l0
aCBYJzBGJyB0byBnZXQgbG93CiAgICAgIC8vIG9yZGVyIGRpZ2l0CiAgICAgIGFuc3dlciArPSBp
MSAqIGRpZ2l0OwogICAgICBkaWdpdCAqPSAxMDsKICAgICAgYW5zd2VyICs9IGkwICogZGlnaXQ7
CiAgICAgIGRpZ2l0ICo9IDEwOwogICAgfQogICAgYW5zd2VyID0gKHBsdXMgPyBhbnN3ZXIgOiAt
MSAqIGFuc3dlcik7IC8vIHJldHVybiBzaWduZWQgcmVzdWx0CiAgfQp9CgpJbnRlZ2VyIHJlc3Vs
dCA9IG5ldyBJbnRlZ2VyKGFuc3dlcik7CgovLyBwaXBlbGluZQppZGMgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsKaWRjLmxhc3QoKTsKaWRjLmluc2VydEFmdGVyKCJpbnRlZ2VyIiwgcmVzdWx0LnRv
U3RyaW5nKCkpOwppZGMuZGVzdHJveSgpOwoK</value>
</Values>
