<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doInvoke</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required serviceNS</value>
    <value>[i] record:0:required input</value>
    <value>[o] record:0:required output</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhIGlu
cHV0RGF0YSA9IG51bGw7CklEYXRhIG91dHB1dERhdGEgPSBudWxsOwpTdHJpbmcgc3RyU2Vydmlj
ZU5hbWUgPSBudWxsOwoKdHJ5CnsKICAvLyAqKiogQ2hlY2sgaWYgc2VydmljZSBpcyBvbiB0aGUg
YWxsb3dlZCBsaXN0ICoqKgogIElEYXRhIGluID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOwogIElE
YXRhQ3Vyc29yIGlkY0luID0gaW4uZ2V0Q3Vyc29yKCk7CiAgaWRjSW4uaW5zZXJ0QWZ0ZXIoInBh
cmFtTmFtZSIsICJhbGxvd2VkU2VydmljZXMiKTsKICBpZGNJbi5pbnNlcnRBZnRlcigicGFyYW1W
YWx1ZSIsIHN0clNlcnZpY2VOYW1lKTsKICBOU05hbWUgbnNDaGVja1NlcnZpY2VOYW1lID0gTlNO
YW1lLmNyZWF0ZSgiUFNVdGlsaXRpZXMuY29uZmlnOmNoZWNrUGFyYW1ldGVyVmFsaWRpdHkiKTsK
ICBpZGNJbi5kZXN0cm95KCk7CiAgSURhdGEgb3V0OwogIG91dCA9IFNlcnZpY2UuZG9JbnZva2Uo
bnNDaGVja1NlcnZpY2VOYW1lLCBpbik7CiAgSURhdGFDdXJzb3IgaWRjT3V0ID0gb3V0LmdldEN1
cnNvcigpOwogIFN0cmluZyBzdHJWYWxpZCA9IG51bGw7CiAgaWYgKGlkY091dC5maXJzdCgidmFs
aWQiKSkKICB7CiAgICBzdHJWYWxpZCA9IChTdHJpbmcpIGlkY091dC5nZXRWYWx1ZSgpOwogIH0K
ICBpZGNPdXQuZGVzdHJveSgpOwoKICBpZiAoc3RyVmFsaWQuZXF1YWxzKCJmYWxzZSIpKQogIHsK
ICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgc2VydmljZSBpcyBub3Qg
b24gdGhlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxl
ISIpOwogIH0KICAvLyAqKiogRW5kIGNoZWNrICoqKgoKICBpZiAoaWRjUGlwZWxpbmUuZmlyc3Qo
InNlcnZpY2VOUyIpKQogIHsKICAgIHN0clNlcnZpY2VOYW1lID0gKFN0cmluZykgaWRjUGlwZWxp
bmUuZ2V0VmFsdWUoKTsKICB9CiAgZWxzZQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJtaXNzaW5nIHNlcnZpY2UgbmFtZSIpOwogIH0KCiAgaWYgKHN0clNlcnZpY2VOYW1lLmxl
bmd0aCgpID09IDApCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBzZXJ2
aWNlIG5hbWUiKTsKCiAgaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJpbnB1dCIpKQogICAgaW5wdXRE
YXRhID0gKElEYXRhKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoKICBOU05hbWUgbnNOYW1lID0g
TlNOYW1lLmNyZWF0ZShzdHJTZXJ2aWNlTmFtZSk7CgogIG91dHB1dERhdGEgPSBTZXJ2aWNlLmRv
SW52b2tlKG5zTmFtZSwgaW5wdXREYXRhKTsKCiAgaWYgKG91dHB1dERhdGEgIT0gbnVsbCkKICAg
IGlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXREYXRhKTsKCn0KY2F0Y2gg
KEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0KZmluYWxs
eQp7CiAgaWRjUGlwZWxpbmUuZGVzdHJveSgpOwp9Cg==</value>
</Values>
