<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deepConvert</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required hashtable</value>
    <value>[o] record:0:required convertedValues</value>
  </array>
  <value name="sigtype">java 3.0</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqCiAqIFRoaXMgbWV0aG9kIHdpbGwgZGVlcCBjb252ZXJ0IGEgSGFzaHRhYmxlIHRvIGEgVmFs
dWVzIG9iamVjdC4gVGhhdCBpcywgaXQKICogd2lsbCBiZSBkZXNpZ25lZCB0byBjb252ZXJ0IGFs
bCBIYXNodGFibGUgb2JqZWN0cyB3aXRoaW4gYSBoYXNodGFibGUsCiAqIG5lc3RlZCBvciBub3Qs
IHRvIGEgdmFsdWVzIG9iamVjdC4KICogCiAqLwoKLy8gR2V0IHRoZSBpbmJvdW5kIEhhc2h0YWJs
ZSBvYmplY3QuCkhhc2h0YWJsZSBoVCA9IChIYXNodGFibGUpIGluLmdldCgiaGFzaHRhYmxlIik7
Cgpib29sZWFuIG51bGxGbGFnID0gZmFsc2U7ClZhbHVlcyBvdXRib3VuZCA9IG5ldyBWYWx1ZXMo
KTsKdHJ5CnsKICAvLyBGb2xsb3dpbmcgc3RhdGVtZW50IGdldHMgYWxsIGFycmF5cyBpbiB0aGlz
IG9iamVjdC4KICBPYmplY3RbXSBoVEFycmF5ID0gaFQudmFsdWVzKCkudG9BcnJheSgpOwogIEVu
dW1lcmF0aW9uIGhURW51bWVyYXRpb24gPSBoVC5rZXlzKCk7CgogIGZvciAoaW50IGkgPSAwOyBp
IDwgaFRBcnJheS5sZW5ndGg7IGkrKykKICB7CiAgICBTdHJpbmcga2V5ID0gKFN0cmluZykgaFRF
bnVtZXJhdGlvbi5uZXh0RWxlbWVudCgpOwogICAgaWYgKGhUQXJyYXlbaV0gaW5zdGFuY2VvZiBq
YXZhLmxhbmcuU3RyaW5nKQogICAgewogICAgICBvdXRib3VuZC5wdXQoa2V5LCAoU3RyaW5nKSBo
VEFycmF5W2ldKTsKICAgIH0KICAgIGVsc2UgaWYgKGhUQXJyYXlbaV0gaW5zdGFuY2VvZiBqYXZh
LnV0aWwuSGFzaHRhYmxlKQogICAgewogICAgICBWYWx1ZXMgaW50ZXJuYWxPYmplY3QgPSBjb252
ZXJ0KChIYXNodGFibGUpIGhUQXJyYXlbaV0pOwogICAgICBpZiAoaW50ZXJuYWxPYmplY3QgPT0g
bnVsbCkKICAgICAgewogICAgICAgIG51bGxGbGFnID0gdHJ1ZTsKICAgICAgICBvdXQucHV0KCJj
b252ZXJ0ZWRWYWx1ZXMiLCBudWxsKTsKICAgICAgICByZXR1cm4gb3V0OwogICAgICB9CiAgICAg
IG91dGJvdW5kLnB1dChrZXksIGludGVybmFsT2JqZWN0KTsKICAgIH0KICAgIGVsc2UKICAgIHsK
ICAgICAgU3lzdGVtLm91dC5wcmludGxuKCJDb252ZXJzaW9uIEZhaWx1cmU6IiArICJ1bnN1cHBv
cnRlZCB0eXBlIHdpdGhpbiBpbmJvdW5kIEhhc2h0YWJsZS4iKTsKICAgICAgb3V0LnB1dCgiY29u
dmVydGVkVmFsdWVzIiwgbnVsbCk7CiAgICAgIHJldHVybiBvdXQ7CiAgICB9CiAgfQp9CmNhdGNo
IChqYXZhLmxhbmcuRXhjZXB0aW9uIGV4KQp7CiAgU3lzdGVtLm91dC5wcmludGxuKCJDb252ZXJz
aW9uIEZhaWx1cmU6IiArIGV4LmdldE1lc3NhZ2UoKSk7CiAgb3V0LnB1dCgiY29udmVydGVkVmFs
dWVzIiwgbnVsbCk7CiAgcmV0dXJuIG91dDsKfQpvdXQucHV0KCJjb252ZXJ0ZWRWYWx1ZXMiLCBv
dXRib3VuZCk7Cg==</value>
</Values>
