<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">concatFields</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:0:required inRecord</value>
    <value>[i] field:1:optional sortOrder</value>
    <value>[i] field:0:optional separator</value>
    <value>[i] field:0:optional skipNulls {"false","true"}</value>
    <value>[o] field:0:required value</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmdCdWZmZXIg
YnVmZmVyID0gbmV3IFN0cmluZ0J1ZmZlcigpOwpTdHJpbmcgc2VwYXJhdG9yID0gbnVsbDsKU3Ry
aW5nW10gc29ydE9yZGVyID0gbnVsbDsKYm9vbGVhbiBza2lwTnVsbHMgPSBJRGF0YVV0aWwuZ2V0
Qm9vbGVhbihjdXJzb3IsICJza2lwTnVsbHMiLCBmYWxzZSk7CgppZiAoY3Vyc29yLmZpcnN0KCJz
ZXBhcmF0b3IiKSkKewogIHNlcGFyYXRvciA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOwp9
CgppZiAoY3Vyc29yLmZpcnN0KCJzb3J0T3JkZXIiKSkKewogIHNvcnRPcmRlciA9IChTdHJpbmdb
XSkgY3Vyc29yLmdldFZhbHVlKCk7Cn0KCklEYXRhIGluUmVjb3JkID0gSURhdGFVdGlsLmdldElE
YXRhKGN1cnNvciwgImluUmVjb3JkIik7CmlmIChpblJlY29yZCA9PSBudWxsKQp7CiAgaW5SZWNv
cmQgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7Cn0KCklEYXRhQ3Vyc29yIGluUmVjb3JkQ3Vyc29y
ID0gaW5SZWNvcmQuZ2V0Q3Vyc29yKCk7Ci8vIElmIG5vIHNvcnRPcmRlciBpcyBzcGVjaWZpZWQs
IGp1c3QgY29uY2F0ZW5hdGUgdGhlIGZpZWxkcyBiYXNlZCBvbiB0aGUKLy8gZGVmYXVsdCBvcmRl
cgppZiAoc29ydE9yZGVyID09IG51bGwgfHwgc29ydE9yZGVyLmxlbmd0aCA9PSAwKQp7CiAgYm9v
bGVhbiBmaXJzdEZpZWxkID0gdHJ1ZTsKICBmb3IgKGludCBpID0gMDsgaW5SZWNvcmRDdXJzb3Iu
bmV4dCgpOyBpKyspCiAgewogICAgU3RyaW5nIHZhbHVlID0gKFN0cmluZykgaW5SZWNvcmRDdXJz
b3IuZ2V0VmFsdWUoKTsKICAgIGlmICh2YWx1ZSA9PSBudWxsKQogICAgewogICAgICB2YWx1ZSA9
ICIiOwogICAgfQoKICAgIGlmIChza2lwTnVsbHMgJiYgKHZhbHVlID09IG51bGwgfHwgdmFsdWUu
bGVuZ3RoKCkgPT0gMCkpCiAgICB7CiAgICAgIGNvbnRpbnVlOwogICAgfQoKICAgIGlmICghZmly
c3RGaWVsZCAmJiBzZXBhcmF0b3IgIT0gbnVsbCkKICAgIHsKICAgICAgYnVmZmVyLmFwcGVuZChz
ZXBhcmF0b3IpOwogICAgfQoKICAgIGJ1ZmZlci5hcHBlbmQodmFsdWUpOwogICAgZmlyc3RGaWVs
ZCA9IGZhbHNlOwogIH0KfQplbHNlCnsKICAvLyBXaGVuIHNvcnRPcmRlciBpcyBzcGVjaWZpZWQs
IHVzZSB0aGF0IHRvIHJldHJpZXZlIGFuZCBjb25jYXRlbmF0ZQogIC8vIGZpZWxkcy4KICBib29s
ZWFuIGZpcnN0RmllbGQgPSB0cnVlOwogIGZvciAoaW50IGkgPSAwOyBpIDwgc29ydE9yZGVyLmxl
bmd0aDsgaSsrKQogIHsKICAgIFN0cmluZyB2YWx1ZSA9ICIiOwogICAgaWYgKGluUmVjb3JkQ3Vy
c29yLmZpcnN0KHNvcnRPcmRlcltpXSkpCiAgICB7CiAgICAgIHZhbHVlID0gKFN0cmluZykgaW5S
ZWNvcmRDdXJzb3IuZ2V0VmFsdWUoKTsKICAgICAgaWYgKHZhbHVlID09IG51bGwpCiAgICAgIHsK
ICAgICAgICB2YWx1ZSA9ICIiOwogICAgICB9CiAgICB9CgogICAgaWYgKHNraXBOdWxscyAmJiAo
dmFsdWUgPT0gbnVsbCB8fCB2YWx1ZS5sZW5ndGgoKSA9PSAwKSkKICAgIHsKICAgICAgY29udGlu
dWU7CiAgICB9CgogICAgaWYgKCFmaXJzdEZpZWxkICYmIHNlcGFyYXRvciAhPSBudWxsKQogICAg
ewogICAgICBidWZmZXIuYXBwZW5kKHNlcGFyYXRvcik7CiAgICB9CgogICAgYnVmZmVyLmFwcGVu
ZCh2YWx1ZSk7CiAgICBmaXJzdEZpZWxkID0gZmFsc2U7CiAgfQp9CgppZiAoYnVmZmVyLmxlbmd0
aCgpID4gMCkKewogIElEYXRhVXRpbC5wdXQoY3Vyc29yLCAidmFsdWUiLCBidWZmZXIudG9TdHJp
bmcoKSk7Cn0KCmN1cnNvci5kZXN0cm95KCk7Cg==</value>
</Values>
