<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertStringToZonedDecimal</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[i] field:0:required length</value>
    <value>[i] field:0:required decimals</value>
    <value>[i] field:0:optional signed {"false","true"}</value>
    <value>[o] field:0:required zonedDecimal</value>
    <value>[o] field:0:optional sign {"+","-"}</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmdCdWZmZXIgc2Ja
b25lZERlY2ltYWwgPSBudWxsOwpTdHJpbmcgc3RyWm9uZWREZWNpbWFsID0gbnVsbDsKaW50IGxl
bmd0aCA9IDA7CmludCBkZWNpbWFscyA9IDA7CmJvb2xlYW4gc2lnbmVkID0gZmFsc2U7ClN0cmlu
ZyBzaWduID0gIisiOwoKaWYgKGlkYy5maXJzdCgic3RyaW5nIikpCnsKICBzdHJab25lZERlY2lt
YWwgPSAoU3RyaW5nKSBpZGMuZ2V0VmFsdWUoKTsKICBzYlpvbmVkRGVjaW1hbCA9IG5ldyBTdHJp
bmdCdWZmZXIoc3RyWm9uZWREZWNpbWFsKTsKfQplbHNlCnsKICBpZGMuaW5zZXJ0QWZ0ZXIoInpv
bmVkRGVjaW1hbCIsIG51bGwpOwogIGlkYy5kZXN0cm95KCk7CiAgcmV0dXJuOwp9CmlmIChpZGMu
Zmlyc3QoImxlbmd0aCIpKQp7CiAgbGVuZ3RoID0gSW50ZWdlci5wYXJzZUludCgoU3RyaW5nKSBp
ZGMuZ2V0VmFsdWUoKSk7Cn0KaWYgKGlkYy5maXJzdCgiZGVjaW1hbHMiKSkKewogIGRlY2ltYWxz
ID0gSW50ZWdlci5wYXJzZUludCgoU3RyaW5nKSBpZGMuZ2V0VmFsdWUoKSk7Cn0KaWYgKGlkYy5m
aXJzdCgic2lnbmVkIikpCnsKICBTdHJpbmcgc3RyU2lnbmVkID0gKFN0cmluZykgaWRjLmdldFZh
bHVlKCk7CiAgaWYgKHN0clNpZ25lZC5lcXVhbHMoInRydWUiKSkKICB7CiAgICBzaWduZWQgPSB0
cnVlOwogIH0KfQoKLy8gUmVtb3ZlIGRlY2ltYWwKaW50IGkgPSBzYlpvbmVkRGVjaW1hbC5pbmRl
eE9mKCIuIik7CmlmIChpID49IDApCnsKICBzYlpvbmVkRGVjaW1hbC5kZWxldGVDaGFyQXQoaSk7
Cn0KQmlnRGVjaW1hbCBiZCA9IG5ldyBCaWdEZWNpbWFsKDApOwppZiAoIXN0clpvbmVkRGVjaW1h
bC50cmltKCkuZXF1YWxzKCIiKSkKewogIGJkID0gbmV3IEJpZ0RlY2ltYWwoc2Jab25lZERlY2lt
YWwudG9TdHJpbmcoKSk7Cn0KZWxzZQp7CiAgaWRjLmluc2VydEFmdGVyKCJ6b25lZERlY2ltYWwi
LCAiIik7CiAgaWRjLmRlc3Ryb3koKTsKICByZXR1cm47Cn0KCmludCBsZW4gPSBzYlpvbmVkRGVj
aW1hbC5sZW5ndGgoKTsKY2hhciBjID0gc2Jab25lZERlY2ltYWwuY2hhckF0KGxlbiAtIDEpOwpj
aGFyIHIgPSBjOwpCaWdEZWNpbWFsIHplcm8gPSBuZXcgQmlnRGVjaW1hbCgwKTsKCmlmIChzaWdu
ZWQpCnsKICBpZiAoYmQuY29tcGFyZVRvKHplcm8pIDwgMCkKICB7CiAgICBzd2l0Y2ggKGMpCiAg
ICB7CiAgICAgIGNhc2UgJzAnOgogICAgICAgIHIgPSAnfSc7CiAgICAgICAgYnJlYWs7CiAgICAg
IGNhc2UgJzEnOgogICAgICAgIHIgPSAnSic7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzIn
OgogICAgICAgIHIgPSAnSyc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzMnOgogICAgICAg
IHIgPSAnTCc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzQnOgogICAgICAgIHIgPSAnTSc7
CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzUnOgogICAgICAgIHIgPSAnTic7CiAgICAgICAg
YnJlYWs7CiAgICAgIGNhc2UgJzYnOgogICAgICAgIHIgPSAnTyc7CiAgICAgICAgYnJlYWs7CiAg
ICAgIGNhc2UgJzcnOgogICAgICAgIHIgPSAnUCc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2Ug
JzgnOgogICAgICAgIHIgPSAnUSc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzknOgogICAg
ICAgIHIgPSAnUic7CiAgICAgICAgYnJlYWs7CiAgICB9CiAgfQogIGVsc2UKICB7CiAgICBzd2l0
Y2ggKGMpCiAgICB7CiAgICAgIGNhc2UgJzAnOgogICAgICAgIHIgPSAneyc7CiAgICAgICAgYnJl
YWs7CiAgICAgIGNhc2UgJzEnOgogICAgICAgIHIgPSAnQSc7CiAgICAgICAgYnJlYWs7CiAgICAg
IGNhc2UgJzInOgogICAgICAgIHIgPSAnQic7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzMn
OgogICAgICAgIHIgPSAnQyc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzQnOgogICAgICAg
IHIgPSAnRCc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzUnOgogICAgICAgIHIgPSAnRSc7
CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2UgJzYnOgogICAgICAgIHIgPSAnRic7CiAgICAgICAg
YnJlYWs7CiAgICAgIGNhc2UgJzcnOgogICAgICAgIHIgPSAnRyc7CiAgICAgICAgYnJlYWs7CiAg
ICAgIGNhc2UgJzgnOgogICAgICAgIHIgPSAnSCc7CiAgICAgICAgYnJlYWs7CiAgICAgIGNhc2Ug
JzknOgogICAgICAgIHIgPSAnSSc7CiAgICAgICAgYnJlYWs7CiAgICB9CiAgfQogIHNiWm9uZWRE
ZWNpbWFsLnNldENoYXJBdChsZW4gLSAxLCByKTsKfQoKaSA9IHNiWm9uZWREZWNpbWFsLmluZGV4
T2YoIi0iKTsKaWYgKGkgPj0gMCkKewogIHNiWm9uZWREZWNpbWFsLmRlbGV0ZUNoYXJBdChpKTsK
ICBzaWduID0gIi0iOwp9CgplbHNlCnsKICBpID0gc2Jab25lZERlY2ltYWwuaW5kZXhPZigiKyIp
OwogIGlmIChpID49IDApCiAgewogICAgc2Jab25lZERlY2ltYWwuZGVsZXRlQ2hhckF0KGkpOwog
IH0KfQpsZW4gPSBzYlpvbmVkRGVjaW1hbC5sZW5ndGgoKTsKd2hpbGUgKGxlbiA8IGxlbmd0aCkK
ewogIHNiWm9uZWREZWNpbWFsLmluc2VydCgwLCAnMCcpOwogIGxlbisrOwp9CgppZGMuaW5zZXJ0
QWZ0ZXIoInpvbmVkRGVjaW1hbCIsIHNiWm9uZWREZWNpbWFsLnRvU3RyaW5nKCkpOwppZiAoIXNp
Z25lZCkKewogIGlkYy5pbnNlcnRBZnRlcigic2lnbiIsIHNpZ24pOwp9CmlkYy5kZXN0cm95KCk7
Cg==</value>
</Values>
