<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipFiles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required sourcePath</value>
    <value>[i] field:0:required zipFileName</value>
    <value>[o] field:0:required numFilesZipped</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBz
dHJTb3VyY2VQYXRoID0gIiI7ClN0cmluZyBzdHJaaXBGaWxlTmFtZSA9ICJkZWZhdWx0LnppcCI7
CgppZiAoaWRjUGlwZWxpbmUuZmlyc3QoInNvdXJjZVBhdGgiKSkKICBzdHJTb3VyY2VQYXRoID0g
KFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJ6
aXBGaWxlTmFtZSIpKQogIHN0clppcEZpbGVOYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0
VmFsdWUoKTsKCi8vICoqKiBDaGVjayBpZiBwYXRocyBhcmUgb24gdGhlIGFsbG93ZWQgbGlzdCAq
KioKdHJ5CnsKICBpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHN0clNvdXJjZVBhdGgsICJyZWFkIikp
CiAgewogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmllZCBwYXRoIGlzIG5v
dCBvbiB0aGUgcmVhZCBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRp
b24gZmlsZSEiKTsKICB9CiAgaWYgKCFjaGVja1BhdGhWYWxpZGl0eShzdHJaaXBGaWxlTmFtZSwg
IndyaXRlIikpCiAgewogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmllZCBw
YXRoIGlzIG5vdCBvbiB0aGUgd3JpdGUgYWxsb3dlZCBsaXN0IGluIHRoZSBQU1V0aWxpdGllcyBj
b25maWd1cmF0aW9uIGZpbGUhIik7CiAgfQp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQovLyAqKiogRW5kIGNoZWNr
ICoqKgoKRmlsZU91dHB1dFN0cmVhbSBmaWxlb3MgPSBudWxsOwpCdWZmZXJlZE91dHB1dFN0cmVh
bSBidWZmaWxlb3MgPSBudWxsOwpaaXBPdXRwdXRTdHJlYW0gemlwb3MgPSBudWxsOwoKaW50IGlu
dE51bUZpbGVzID0gMDsKdHJ5CnsKICBmaWxlb3MgPSBuZXcgRmlsZU91dHB1dFN0cmVhbShzdHJa
aXBGaWxlTmFtZSk7CiAgYnVmZmlsZW9zID0gbmV3IEJ1ZmZlcmVkT3V0cHV0U3RyZWFtKGZpbGVv
cyk7CiAgemlwb3MgPSBuZXcgWmlwT3V0cHV0U3RyZWFtKGJ1ZmZpbGVvcyk7CgogIEZpbGUgZmls
ZVNvdXJjZVBhdGggPSBuZXcgRmlsZShzdHJTb3VyY2VQYXRoKTsKICBpZiAoZmlsZVNvdXJjZVBh
dGguaXNEaXJlY3RvcnkoKSkKICB7CiAgICBpbnROdW1GaWxlcyA9IGFkZERpcmVjdG9yeVRvWmlw
KHN0clNvdXJjZVBhdGgsICIiLCB6aXBvcyk7CiAgfQogIGVsc2UKICAvLyBmaWxlCiAgewogICAg
Ly8gR2V0IGZpbGVuYW1lLCB3aXRob3V0IHBhdGgKICAgIGludCBpbmRleCA9IHN0clNvdXJjZVBh
dGgubGFzdEluZGV4T2YoU3lzdGVtLmdldFByb3BlcnR5KCJmaWxlLnNlcGFyYXRvciIpKTsKICAg
IFN0cmluZyBzdHJGaWxlbmFtZSA9IHN0clNvdXJjZVBhdGguc3Vic3RyaW5nKGluZGV4ICsgMSk7
CgogICAgYWRkRmlsZVRvWmlwKHN0clNvdXJjZVBhdGgsIHN0ckZpbGVuYW1lLCB6aXBvcyk7CiAg
ICBpbnROdW1GaWxlcysrOwogIH0KfQpjYXRjaCAoSU9FeGNlcHRpb24gZSkKewogIHRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKCJFeGNlcHRpb24gb2NjdXJyZWQgd2hpbGUgY3JlYXRpbmcgWklQ
IGZpbGU6ICIgKyBlKTsKfQpmaW5hbGx5CnsKICBpZiAoemlwb3MgIT0gbnVsbCkKICB7CiAgICB0
cnkKICAgIHsKICAgICAgemlwb3MuY2xvc2UoKTsKICAgIH0KICAgIGNhdGNoIChJT0V4Y2VwdGlv
biBlKQogICAgewogICAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRXhjZXB0aW9uIG9j
Y3VycmVkIHdoaWxlIGNyZWF0aW5nIFpJUCBmaWxlOiAiICsgZSk7CiAgICB9CiAgfQogIGlmIChm
aWxlb3MgIT0gbnVsbCkKICB7CiAgICB0cnkKICAgIHsKICAgICAgZmlsZW9zLmNsb3NlKCk7CiAg
ICB9CiAgICBjYXRjaCAoSU9FeGNlcHRpb24gZSkKICAgIHsKICAgICAgdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oIkV4Y2VwdGlvbiBvY2N1cnJlZCB3aGlsZSBjcmVhdGluZyBaSVAgZmlsZTog
IiArIGUpOwogICAgfQogIH0KICBpZiAoYnVmZmlsZW9zICE9IG51bGwpCiAgewogICAgdHJ5CiAg
ICB7CiAgICAgIGJ1ZmZpbGVvcy5mbHVzaCgpOwogICAgICBidWZmaWxlb3MuY2xvc2UoKTsKICAg
IH0KICAgIGNhdGNoIChJT0V4Y2VwdGlvbiBlKQogICAgewogICAgICB0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbigiRXhjZXB0aW9uIG9jY3VycmVkIHdoaWxlIGNyZWF0aW5nIFpJUCBmaWxlOiAi
ICsgZSk7CiAgICB9CiAgfQp9CgppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigibnVtRmlsZXNaaXBw
ZWQiLCBJbnRlZ2VyLnRvU3RyaW5nKGludE51bUZpbGVzKSk7CmlkY1BpcGVsaW5lLmRlc3Ryb3ko
KTsK</value>
</Values>
