<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">moveFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required sourcePath</value>
    <value>[i] field:0:required targetDir</value>
    <value>[i] field:0:required useTimeStamp {"false","true"}</value>
    <value>[o] field:0:required status</value>
    <value>[o] field:0:required targetFilePath</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcgc291cmNl
UGF0aCA9IG51bGw7ClN0cmluZyB0YXJnZXREaXIgPSBudWxsOwoKaWYgKGN1cnNvci5maXJzdCgi
c291cmNlUGF0aCIpKQp7CiAgc291cmNlUGF0aCA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgp
Owp9CmVsc2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBwYXJhbWV0ZXIg
XCdzb3VyY2VQYXRoXCcgd2FzIG5vdCBmb3VuZC4iKTsKfQppZiAoY3Vyc29yLmZpcnN0KCJ0YXJn
ZXREaXIiKSkKewogIHRhcmdldERpciA9IChTdHJpbmcpIGN1cnNvci5nZXRWYWx1ZSgpOwp9CmVs
c2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBwYXJhbWV0ZXIgXCd0YXJn
ZXREaXJcJyB3YXMgbm90IGZvdW5kLiIpOwp9CmJvb2xlYW4gdXNlVGltZVN0YW1wID0gY3Vyc29y
LmZpcnN0KCJ1c2VUaW1lU3RhbXAiKSA/IEJvb2xlYW4udmFsdWVPZigoU3RyaW5nKSBjdXJzb3Iu
Z2V0VmFsdWUoKSkuYm9vbGVhblZhbHVlKCkgOiBmYWxzZTsKY3Vyc29yLmRlc3Ryb3koKTsKCi8v
ICoqKiBDaGVjayBpZiBwYXRocyBhcmUgb24gdGhlIGFsbG93ZWQgbGlzdCAqKioKdHJ5CnsKICBp
ZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHNvdXJjZVBhdGgsICJyZWFkIikpCiAgewogICAgdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmllZCBwYXRoIGlzIG5vdCBvbiB0aGUgcmVhZCBh
bGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsKICB9
CiAgaWYgKCFjaGVja1BhdGhWYWxpZGl0eSh0YXJnZXREaXIsICJ3cml0ZSIpKQogIHsKICAgIHRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgcGF0aCBpcyBub3Qgb24gdGhlIHdy
aXRlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlISIp
OwogIH0KfQpjYXRjaCAoRXhjZXB0aW9uIGUpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bihlLmdldE1lc3NhZ2UoKSk7Cn0KLy8gKioqIEVuZCBjaGVjayAqKioKCmJvb2xlYW4gc3RhdHVz
ID0gZmFsc2U7CkZpbGUgb3JpZ2luYWwgPSBuZXcgRmlsZShzb3VyY2VQYXRoKTsKCi8vIFN0cmlu
ZyBkdFN0YW1wID0gbmV3IERhdGUoKS50b1N0cmluZygpLnJlcGxhY2UoJyAnLCAnLScpLnJlcGxh
Y2UoJzonLAovLyAnLScpOwpTdHJpbmcgZHRTdGFtcCA9IG51bGw7CnRyeQp7CiAgSURhdGEgZCA9
IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKICBJRGF0YUN1cnNvciBjID0gZC5nZXRDdXJzb3IoKTsK
ICBjLmZpcnN0KCk7CiAgYy5pbnNlcnRCZWZvcmUoInBhdHRlcm4iLCAieXl5eU1NZGRISG1tc3Mi
KTsKICBJRGF0YSBkMiA9IFNlcnZpY2UuZG9JbnZva2UoInB1Yi5kYXRlIiwgImN1cnJlbnREYXRl
IiwgZCk7CiAgYyA9IGQyLmdldEN1cnNvcigpOwogIGlmIChjLmZpcnN0KCJ2YWx1ZSIpKQogIHsK
ICAgIGR0U3RhbXAgPSAoU3RyaW5nKSBjLmdldFZhbHVlKCk7CiAgfQogIGVsc2UKICB7CiAgICB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTWlzc2luZyByZXR1cm5lZCB2YWx1ZSBmb3IgU2Vy
dmljZSBjdXJyZW50RGF0ZS4iKTsKICB9Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9ClN0cmluZyBiYXNlbmFtZSA9
IG9yaWdpbmFsLmdldE5hbWUoKTsKaWYgKHVzZVRpbWVTdGFtcCkKewogIGJhc2VuYW1lICs9ICIt
IiArIGR0U3RhbXA7Cn0KRmlsZSB0YXJnZXRGaWxlID0gbmV3IEZpbGUodGFyZ2V0RGlyLCBiYXNl
bmFtZSk7CnN0YXR1cyA9IG9yaWdpbmFsLnJlbmFtZVRvKHRhcmdldEZpbGUpOwpTdHJpbmcgdGFy
Z2V0RmlsZVBhdGggPSBudWxsOwp0cnkKewogIHRhcmdldEZpbGVQYXRoID0gdGFyZ2V0RmlsZS5n
ZXRDYW5vbmljYWxQYXRoKCk7Cn0KY2F0Y2ggKElPRXhjZXB0aW9uIGUpCnsKICB0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiTW92ZSBmaWxlIGFuZCBvYnRhaW4gdGFyZ2V0IHBhdGg6ICIgKyBl
LmdldE1lc3NhZ2UoKSk7Cn0KY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CmN1cnNvci5s
YXN0KCk7CmN1cnNvci5pbnNlcnRBZnRlcigic3RhdHVzIiwgIiIgKyBzdGF0dXMpOwpjdXJzb3Iu
aW5zZXJ0QWZ0ZXIoInRhcmdldEZpbGVQYXRoIiwgdGFyZ2V0RmlsZVBhdGgpOwpjdXJzb3IuZGVz
dHJveSgpOwo=</value>
</Values>
