<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServiceName</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:0:required folderName</value>
    <value>[o] field:0:required serviceName</value>
    <value>[o] field:0:required fullName</value>
    <value>[o] field:0:required successFlag</value>
    <value>[o] field:0:required errorMessage</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqCiAqIFNlcnZpY2UgaXMgZGVzaWduZWQgdG8gcmV0dXJuIHRoZSBjdXJyZW50IHNlcnZpY2Ug
bmFtZS4gT3V0cHV0OgogKiBmb2xkZXJQYXRoIC0gdGhlIGZvbGRlciBwYXRoIHRvIHRoZSBzZXJ2
aWNlIHNlcnZpY2VOYW1lIC0gdGhlIHNlcnZpY2UKICogbmFtZSBmdWxsTmFtZSAtIHRoZSBmb2xk
ZXIgcGF0aCArICI6IiArIHNlcnZpY2Ugc3VjY2Vzc0ZsYWcgLSB0cnVlIG9yCiAqIGZhbHNlIGVy
cm9yTWVzc2FnZSAtIGVycm9yIGRldGFpbC4gVGhpcyBpcyBzZXQgdG8gIk5vbmUiIGlmIG5vIGVy
cm9yCiAqIG9jY3Vycy4KICogCiAqIE5PVEUgMTogQmVjYXVzZSB0aGlzIHNlcnZpY2UgcmVsaWVz
IG9uIGEgbWV0aG9kIGludm9jYXRpb24gdGhhdCByZXRyaWV2ZXMKICogdGhlIE5TU2VydmljZSBv
YmplY3QgcmVsYXRpbmcgdG8gdGhlIGNhbGxpbmcgc2VydmljZSwgaXQgd2lsbCAqTk9UKiB3b3Jr
CiAqIGFzIGRlc2lyZWQgaWYgcnVuIGluZGVwZW5kZW50bHkuIEluc3RlYWQsIGl0IHdpbGwgcmV0
dXJuIGluZm9ybWF0aW9uIG9uCiAqIHRoZSBjdXJyZW50IHNlcnZpY2UgKHRoaXMgb25lKSBhbmQg
c2V0IHRoZSAic3VjY2Vzc0ZsYWciIGFuZAogKiAiZXJyb3JNZXNzYWdlIiB2YWx1ZXMgdG8gaW5k
aWNhdGUgYW4gZXJyb3IuIE5PVEUgMjogVGhpcyBzZXJ2aWNlIHVzZXMKICogbm9uLXB1YmxpYyBB
UElzIHdpdGhpbiB0aGUgd2ViTWV0aG9kcyBJbnRlZ3JhdGlvbiBTZXJ2ZXIuIFRoZXNlIG1heQog
KiBjaGFuZ2UgaW4gZnV0dXJlIHJlbGVhc2VzIG9mIHRoZSBwcm9kdWN0ICp3aXRob3V0KiBub3Rp
Y2UuIFRoZXNlIG1ldGhvZAogKiBpbnZvY2F0aW9ucyBhcmUgbWFya2VkIGFzIHN1Y2guCiAqIAog
Ki8KCi8vIEluc3RhbnRpYXRlIGEgY3Vyc29yIGZvciBhY2Nlc3MgdG8gdGhlIHBpcGVsaW5lCklE
YXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgovLyBXb3Jr
aW5nICYgT3V0cHV0IFZhcmlhYmxlcyAtIENyZWF0ZSBhbGwgb3V0cHV0ICYgd29ya2luZyB2YXJp
YWJsZXMKTlNTZXJ2aWNlIGNhbGxpbmdTZXJ2aWNlID0gbnVsbDsKU3RyaW5nVG9rZW5pemVyIHN0
clRvayA9IG51bGw7ClN0cmluZyBmb2xkZXJQYXRoID0gbmV3IFN0cmluZygpOwpTdHJpbmcgc2Vy
dmljZU5hbWUgPSBuZXcgU3RyaW5nKCk7ClN0cmluZyBmdWxsTmFtZSA9IG5ldyBTdHJpbmcoKTsK
U3RyaW5nIHN1Y2Nlc3NGbGFnID0gInRydWUiOwpTdHJpbmcgZXJyb3JNZXNzYWdlID0gIk5vbmUi
OwoKLy8gSW5wdXQgVmFyaWFibGVzCi8vIE5vbmUKCi8vIFNlcnZpY2UgQm9keQovLyBUaGlzIHB1
YmxpY2x5IGRvY3VtZW50ZWQgbWV0aG9kIGdldHMgdGhlIE5TU2VydmljZSBvYmplY3QgYXNzb2Np
YXRlZCB3aXRoCi8vIHRoZSBjYWxsaW5nIHNlcnZpY2UuCmNhbGxpbmdTZXJ2aWNlID0gU2Vydmlj
ZS5nZXRDYWxsaW5nU2VydmljZSgpOwoKLyoqCiAqIElmIHRoZSBjYWxsaW5nU2VydmljZSBpcyBu
b3QgYXZhaWxhYmxlIChtZWFuaW5nIHRoYXQgdGhlIHNlcnZpY2Ugd2FzIHJ1bgogKiBkaXJlY3Rs
eSwgc2V0IHRoZSAiY2FsbGluZ1NlcnZpY2UiIHRvIGhvbGQgdGhlIHZhbHVlcyBmb3IgdGhlIGN1
cnJlbnQKICogc2VydmljZSAodGhpcyBvbmUpLiBBZGRpdGlvbmFsbHksIHNldCB0aGUgInN1Y2Nl
c3NGbGFnIiBhbmQKICogImVycm9yTWVzc2FnZSIgZmllbGRzIHRvIGluZGljYXRlIGEgcHJvYmxl
bS4KICovCmlmIChjYWxsaW5nU2VydmljZSA9PSBudWxsKQp7CiAgY2FsbGluZ1NlcnZpY2UgPSBJ
bnZva2VTdGF0ZS5nZXRDdXJyZW50U2VydmljZSgpOwogIHN1Y2Nlc3NGbGFnID0gImZhbHNlIjsK
ICBlcnJvck1lc3NhZ2UgPSAiTm8gY2FsbGluZyBzZXJ2aWNlIGZvdW5kLi4uIFJldHVybmluZyBp
bmZvcm1hdGlvbiBmb3IgdGhpcyBzZXJ2aWNlIGluc3RlYWQuIjsKfQoKLyoqCiAqIE5vbi1wdWJs
aWMgQVBJLiBIb3dldmVyLCB0aGlzIGNhbGwgaXMgcmVsYXRpdmVseSBzYWZlLCBhcyAidG9TdHJp
bmciIGlzIGEKICogc3RhbmRhcmQgbWV0aG9kIHRoYXQgaXMgbm9ybWFsbHkgb3ZlcnJpZGVuIGZy
b20gdGhlIHJvb3QKICogamF2YS5sYW5nLk9iamVjdC4KICovCmZ1bGxOYW1lID0gY2FsbGluZ1Nl
cnZpY2UudG9TdHJpbmcoKTsKCi8qKgogKiBVc2UgU3RyaW5nVG9rZW5pemVyLCBmcm9tIHRoZSBq
YXZhLnV0aWwgcGFja2FnZSwgdG8gZXh0cmFjdCB0aGUKICogZm9sZGVyUGF0aCBhbmQgc2Vydmlj
ZU5hbWUgdmFsdWVzLgogKi8KdHJ5CnsKICBzdHJUb2sgPSBuZXcgU3RyaW5nVG9rZW5pemVyKGZ1
bGxOYW1lLCAiOiIpOwogIGZvbGRlclBhdGggPSBzdHJUb2submV4dFRva2VuKCk7CiAgc2Vydmlj
ZU5hbWUgPSBzdHJUb2submV4dFRva2VuKCk7Cn0KY2F0Y2ggKGphdmEubGFuZy5FeGNlcHRpb24g
ZXgpCnsKICBTeXN0ZW0ub3V0LnByaW50bG4oIkNSSVRJQ0FMIEVSUk9SOiBDaGVjayB0aGUgdG9T
dHJpbmcoKSBtZXRob2Qgd2l0aGluIE5TU2VydmljZSB0byBlbnN1cmUgdGhhdCBpdCBpcyByZXR1
cm5pbmcgRm9sZGVyOlNlcnZpY2VOYW1lIGFzIGRlc2lyZWQuIik7CiAgc3VjY2Vzc0ZsYWcgPSAi
ZmFsc2UiOwogIGVycm9yTWVzc2FnZSA9ICJDUklUSUNBTCBFUlJPUjogQ2hlY2sgdGhlIHRvU3Ry
aW5nKCkgbWV0aG9kIHdpdGhpbiBOU1NlcnZpY2UgdG8gZW5zdXJlIHRoYXQgaXQgaXMgcmV0dXJu
aW5nIEZvbGRlcjpTZXJ2aWNlTmFtZSBhcyBkZXNpcmVkLiI7Cgp9CgovLyBQb3B1bGF0ZSBzZXJ2
aWNlIG91dHB1dAppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoImZvbGRlclBhdGgiKSkKICBwaXBl
bGluZUN1cnNvci5kZWxldGUoKTsKcGlwZWxpbmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoImZvbGRlclBh
dGgiLCBmb2xkZXJQYXRoKTsKCmlmIChwaXBlbGluZUN1cnNvci5maXJzdCgic2VydmljZU5hbWUi
KSkKICBwaXBlbGluZUN1cnNvci5kZWxldGUoKTsKcGlwZWxpbmVDdXJzb3IuaW5zZXJ0QWZ0ZXIo
InNlcnZpY2VOYW1lIiwgc2VydmljZU5hbWUpOwoKaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0KCJm
dWxsTmFtZSIpKQogIHBpcGVsaW5lQ3Vyc29yLmRlbGV0ZSgpOwpwaXBlbGluZUN1cnNvci5pbnNl
cnRBZnRlcigiZnVsbE5hbWUiLCBmdWxsTmFtZSk7CgppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3Qo
InN1Y2Nlc3NGbGFnIikpCiAgcGlwZWxpbmVDdXJzb3IuZGVsZXRlKCk7CnBpcGVsaW5lQ3Vyc29y
Lmluc2VydEFmdGVyKCJzdWNjZXNzRmxhZyIsIHN1Y2Nlc3NGbGFnKTsKCmlmIChwaXBlbGluZUN1
cnNvci5maXJzdCgiZXJyb3JNZXNzYWdlIikpCiAgcGlwZWxpbmVDdXJzb3IuZGVsZXRlKCk7CnBp
cGVsaW5lQ3Vyc29yLmluc2VydEFmdGVyKCJlcnJvck1lc3NhZ2UiLCBlcnJvck1lc3NhZ2UpOwo=
</value>
</Values>
