<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">subtractDoubles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required number1</value>
    <value>[i] field:0:required number2</value>
    <value>[i] field:0:optional scale</value>
    <value>[o] field:0:required result</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqCiAqIFNlcnZpY2UgcmVwbGFjZXMgcHViLm1hdGg6c3VidHJhY3RGbG9hdHMsIGFzIHRoYXQg
c2VydmljZSBzdWZmZXJzIGZyb20KICogaXNzdWVzIHdpdGggdGhlIGNvcmUgSlZNJ3MgaGFuZGxp
bmcgb2YgdGhlIHN1YnRyYWN0aW9uIG9mIGZsb2F0aW5nLXBvaW50CiAqIG51bWJlcnMuIFNlcnZp
Y2UgdGFrZXMgdGhyZWUgaW5wdXRzOiBudW1iZXIxOiBUaGUgbnVtYmVyIGZyb20gd2hpY2ggdGhl
CiAqIHNlY29uZCBpcyB0byBiZSBzdWJ0cmFjdGVkLiBNdXN0IGJlIGEgZG91YmxlLiBudW1iZXIy
OiBUaGUgbnVtYmVyIHRvIGJlCiAqIHN1YnRyYWN0ZWQgZnJvbSB0aGUgZmlyc3QuIE11c3QgYmUg
YSBkb3VibGUuIHNjYWxlIChvcHRpb25hbCk6IFRoZSBzY2FsZQogKiBvZiB0aGUgcmVzdWx0LiBE
ZWZhdWx0cyB0byA1LgogKiAKICogVGhlICJyZXN1bHQiIHdpbGwgYmUgYSBTdHJpbmcgdGhhdCBj
b250YWlucyBhIGRvdWJsZSB3aXRoIHRoZSBzcGVjaWZpZWQKICogc2NhbGUuCiAqIAogKiBBbnkg
ZXJyb3JzIGVuY291bnRlcmVkIHdpbGwgY2F1c2UgYQogKiBjb20ud20uYXBwLmIyYi5zZXJ2ZXIu
U2VydmljZUV4Y2VwdGlvbiB0byBiZSB0aHJvd24uCiAqIAogKiAqKk5PVEUqKjogRW1waXJpY2Fs
IGV2aWRlbmNlIHNob3dzIHRoYXQgcmVzdWx0cyBtYXkgYmVnaW4gdG8gbG9zZSB0aGVpcgogKiBy
ZWxpYWJpbGl0eSBhdCBsYXJnZXIgc2NhbGVzLiBTY2FsZXMgbG93ZXIgdGhhbiAxMCBzZWVtIHRv
IHdvcmsgZmluZSBpbgogKiBsaW1pdGVkIHRlc3RpbmcuCiAqIAogKi8KCi8vIEluc3RhbnRpYXRl
IGEgY3Vyc29yIGZvciBhY2Nlc3MgdG8gdGhlIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5l
Q3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgovLyBDcmVhdGUgYWxsIG91dHB1dCAmIHdv
cmtpbmcgdmFyaWFibGVzClN0cmluZyBudW1iZXIxU3RyaW5nID0gbmV3IFN0cmluZygpOwpkb3Vi
bGUgbnVtYmVyMTsKU3RyaW5nIG51bWJlcjJTdHJpbmcgPSBuZXcgU3RyaW5nKCk7CmRvdWJsZSBu
dW1iZXIyOwpTdHJpbmcgcmVzdWx0U3RyaW5nID0gbmV3IFN0cmluZygpOwpkb3VibGUgcmVzdWx0
OwpTdHJpbmcgc2NhbGVTdHJpbmcgPSBuZXcgU3RyaW5nKCk7CmludCBzY2FsZTsKaW50IHdvcmtp
bmdTY2FsZTsKQmlnRGVjaW1hbCBiRE51bWJlcjE7CkJpZ0RlY2ltYWwgYkROdW1iZXIyOwpCaWdE
ZWNpbWFsIGJEUmVzdWx0OwoKLy8gSW5wdXQgVmFyaWFibGVzCmlmIChwaXBlbGluZUN1cnNvci5m
aXJzdCgibnVtYmVyMSIpID09IGZhbHNlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
Ik5vIHZhbHVlIHdhcyBzcGVjaWZpZWQgZm9yIFwibnVtYmVyMVwiLiIpOwp9Cm51bWJlcjFTdHJp
bmcgPSAoU3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp0cnkKewogIG51bWJlcjEg
PSAoRG91YmxlLnZhbHVlT2YobnVtYmVyMVN0cmluZykpLmRvdWJsZVZhbHVlKCk7Cn0KY2F0Y2gg
KE51bWJlckZvcm1hdEV4Y2VwdGlvbiBuZkV4KQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlRoZSBpbnB1dCB2YXJpYWJsZSBcIm51bWJlcjFcIiBtdXN0IGJlIGEgZmxvYXQgb3IgIiAr
ICJhIGRvdWJsZS4iKTsKfQoKaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0KCJudW1iZXIyIikgPT0g
ZmFsc2UpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTm8gdmFsdWUgd2FzIHNwZWNp
ZmllZCBmb3IgXCJudW1iZXIyXCIuIik7Cn0KbnVtYmVyMlN0cmluZyA9IChTdHJpbmcpIHBpcGVs
aW5lQ3Vyc29yLmdldFZhbHVlKCk7CnRyeQp7CiAgbnVtYmVyMiA9IChEb3VibGUudmFsdWVPZihu
dW1iZXIyU3RyaW5nKSkuZG91YmxlVmFsdWUoKTsKfQpjYXRjaCAoTnVtYmVyRm9ybWF0RXhjZXB0
aW9uIG5mRXgpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVGhlIGlucHV0IHZhcmlh
YmxlIFwibnVtYmVyMlwiIG11c3QgYmUgYSBmbG9hdCBvciAiICsgImEgZG91YmxlLiIpOwp9Cgpp
ZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInNjYWxlIikgPT0gZmFsc2UpCnsKICAvLyBzY2FsZSBp
cyBub3QgbWFuZGF0b3J5LiBEZWZhdWx0IHRvIDUuCiAgc2NhbGUgPSA1Owp9CmVsc2UKewogIHNj
YWxlU3RyaW5nID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKICB0cnkKICB7
CiAgICBzY2FsZSA9IChJbnRlZ2VyLnZhbHVlT2Yoc2NhbGVTdHJpbmcpKS5pbnRWYWx1ZSgpOwog
IH0KICBjYXRjaCAoTnVtYmVyRm9ybWF0RXhjZXB0aW9uIG5mRXgpCiAgewogICAgdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oIlRoZSBpbnB1dCB2YXJpYWJsZSBcInNjYWxlXCIgbXVzdCBiZSBh
biAiICsgImludGVnZXIuIik7CiAgfQp9CgovLyBDcmVhdGUgdGhlIEJpZ0RlY2ltYWwgb2JqZWN0
cyByZXByZXNlbnRpbmcgdGhlIG51bWJlcnMgdGhhdCB3ZXJlCi8vIHByb3ZpZGVkLgpiRE51bWJl
cjEgPSBuZXcgQmlnRGVjaW1hbChudW1iZXIxKTsKYkROdW1iZXIyID0gbmV3IEJpZ0RlY2ltYWwo
bnVtYmVyMik7CgovLyBTZXJ2aWNlIGJvZHkKLyoKICogU2V0IHNjYWxlLiBUaGlzIGlzIGNyaXRp
Y2FsLCBhbmQgaXQgaXMgdGhpcyBzdGF0ZW1lbnQgdGhhdCBkZWZlYXRzIHRoZQogKiBKVk0gYnVn
IHdoZXJlIGZsb2F0aW5nLXBvaW50IHJlc3VsdHMgYXJlIHVucHJlZGljdGFibGUuCiAqLwpiRE51
bWJlcjEgPSBiRE51bWJlcjEuc2V0U2NhbGUoc2NhbGUsIEJpZ0RlY2ltYWwuUk9VTkRfSEFMRl9V
UCk7CgovLyBDb21wdXRlIHRoZSAicmVzdWx0Ii4KYkRSZXN1bHQgPSBiRE51bWJlcjEuc3VidHJh
Y3QoYkROdW1iZXIyKTsKCi8qCiAqIFNldCBzY2FsZS4gVGhpcyBpcyBjcml0aWNhbCwgYW5kIGl0
IGlzIHRoaXMgc3RhdGVtZW50IHRoYXQgZGVmZWF0cyB0aGUKICogSlZNIGJ1ZyB3aGVyZSBmbG9h
dGluZy1wb2ludCByZXN1bHRzIGFyZSB1bnByZWRpY3RhYmxlLgogKi8KYkRSZXN1bHQgPSBiRFJl
c3VsdC5zZXRTY2FsZShzY2FsZSwgQmlnRGVjaW1hbC5ST1VORF9IQUxGX1VQKTsKCnJlc3VsdCA9
IGJEUmVzdWx0LmRvdWJsZVZhbHVlKCk7CnJlc3VsdFN0cmluZyA9IFN0cmluZy52YWx1ZU9mKHJl
c3VsdCk7CgovLyBQb3B1bGF0ZSBzZXJ2aWNlIG91dHB1dAppZiAocGlwZWxpbmVDdXJzb3IuZmly
c3QoInJlc3VsdCIpKQogIHBpcGVsaW5lQ3Vyc29yLmRlbGV0ZSgpOwpwaXBlbGluZUN1cnNvci5p
bnNlcnRBZnRlcigicmVzdWx0IiwgcmVzdWx0U3RyaW5nKTsKcGlwZWxpbmVDdXJzb3IuZGVzdHJv
eSgpOwo=</value>
</Values>
