<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listFiles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required directory</value>
    <value>[i] field:0:optional filter</value>
    <value>[o] field:1:required fileList</value>
    <value>[o] field:1:required fileList_fullpathnames</value>
    <value>[o] field:0:required numFiles</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKClN0cmluZyBm
aWx0ZXJTdHJpbmcgPSBudWxsOwppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZpbHRlciIpKQp7CiAg
ZmlsdGVyU3RyaW5nID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQoKU3RyaW5n
IGRpcmVjdG9yeSA9IG51bGw7CmlmIChpZGNQaXBlbGluZS5maXJzdCgiZGlyZWN0b3J5IikpCnsK
ICBkaXJlY3RvcnkgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CmVsc2UKewog
IHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJEaXJlY3RvcnkgaXMgbnVsbCEiKTsKfQoKU3Ry
aW5nIHN0ckZpbGVTZXBhcmF0b3IgPSBTeXN0ZW0uZ2V0UHJvcGVydHkoImZpbGUuc2VwYXJhdG9y
Iik7CmludCBudW1GaWxlcyA9IDA7CgovLyAqKiogQ2hlY2sgaWYgcGF0aCBpcyBvbiB0aGUgYWxs
b3dlZCBsaXN0ICoqKgp0cnkKewogIGlmICghY2hlY2tQYXRoVmFsaWRpdHkoZGlyZWN0b3J5LCAi
cmVhZCIpKQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgcGF0
aCBpcyBub3Qgb24gdGhlIHJlYWQgYWxsb3dlZCBsaXN0IGluIHRoZSBQU1V0aWxpdGllcyBjb25m
aWd1cmF0aW9uIGZpbGUhIik7CiAgfQp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQovLyAqKiogRW5kIGNoZWNrICoq
KgoKRmlsZSBkaXIgPSBuZXcgRmlsZShkaXJlY3RvcnkpOwoKaWYgKCFkaXIuZXhpc3RzKCkgfHwg
IWRpci5pc0RpcmVjdG9yeSgpKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9y
IHJlYWRpbmcgaW5ib3ggZGlyZWN0b3J5ISIpOwp9CgpTdHJpbmcgZGlyX2xpc3RbXTsKaWYgKChm
aWx0ZXJTdHJpbmcgIT0gbnVsbCkgJiYgZmlsdGVyU3RyaW5nLmxlbmd0aCgpID4gMCkKewogIEpa
T09XaWxkQ2FyZEZpbHRlciBmaWx0ZXIgPSBuZXcgSlpPT1dpbGRDYXJkRmlsdGVyKGZpbHRlclN0
cmluZyk7CiAgZGlyX2xpc3QgPSBkaXIubGlzdChmaWx0ZXIpOwp9CmVsc2UKewogIGRpcl9saXN0
ID0gZGlyLmxpc3QoKTsKfQppbnQgbnVtX2ZpbGVzYW5kZGlyID0gZGlyX2xpc3QubGVuZ3RoOwoK
aWYgKG51bV9maWxlc2FuZGRpciA8IDEpIC8vIE5vIGZpbGVzIHRvIHNlbmQKewogIGlkY1BpcGVs
aW5lLmluc2VydEFmdGVyKCJudW1GaWxlcyIsIEludGVnZXIudG9TdHJpbmcobnVtRmlsZXMpKTsK
ICByZXR1cm47Cn0KCi8vIERldGVybWluZSBudW1iZXIgb2YgYWN0dWFsIGZpbGVzCkZpbGUgY3Vy
cl9maWxlOwpmb3IgKGludCBpID0gMDsgaSA8IG51bV9maWxlc2FuZGRpcjsgaSsrKQp7CiAgY3Vy
cl9maWxlID0gbmV3IEZpbGUoZGlyZWN0b3J5ICsgc3RyRmlsZVNlcGFyYXRvciArIGRpcl9saXN0
W2ldKTsKICBpZiAoY3Vycl9maWxlLmlzRmlsZSgpKQogIHsKICAgIG51bUZpbGVzKys7CiAgfQp9
CmN1cnJfZmlsZSA9IG51bGw7CgovLyBDcmVhdGUgYXJyYXkgd2l0aCBvbmx5IG5hbWVzIG9mIGZp
bGVzIChleGNsdWRpbmcgZGlyZWN0b3JpZXMpClN0cmluZ1tdIGZpbGVMaXN0ID0gbmV3IFN0cmlu
Z1tudW1GaWxlc107ClN0cmluZ1tdIGZpbGVMaXN0X2Z1bGxwYXRobmFtZXMgPSBuZXcgU3RyaW5n
W251bUZpbGVzXTsKbnVtRmlsZXMgPSAwOwpmb3IgKGludCBpID0gMDsgaSA8IG51bV9maWxlc2Fu
ZGRpcjsgaSsrKQp7CiAgY3Vycl9maWxlID0gbmV3IEZpbGUoZGlyZWN0b3J5ICsgc3RyRmlsZVNl
cGFyYXRvciArIGRpcl9saXN0W2ldKTsKICBpZiAoY3Vycl9maWxlLmlzRmlsZSgpKQogIHsKICAg
IGZpbGVMaXN0W251bUZpbGVzXSA9IGRpcl9saXN0W2ldOwoKICAgIC8vIEFzc2VtYmxlIGZ1bGx5
IHF1YWxpZmllZCBmaWxlbmFtZXMgKGNoZWNrIFVOSVggJiBOVCkKICAgIGNoYXIgbGFzdENoYXIg
PSBkaXJlY3RvcnkuY2hhckF0KGRpcmVjdG9yeS5sZW5ndGgoKSAtIDEpOwogICAgaWYgKChsYXN0
Q2hhciA9PSAnXFwnKSB8fCAobGFzdENoYXIgPT0gJy8nKSkKICAgIHsKICAgICAgZmlsZUxpc3Rf
ZnVsbHBhdGhuYW1lc1tudW1GaWxlc10gPSBkaXJlY3RvcnkgKyBkaXJfbGlzdFtpXTsKICAgIH0K
ICAgIGVsc2UKICAgIHsKICAgICAgZmlsZUxpc3RfZnVsbHBhdGhuYW1lc1tudW1GaWxlc10gPSBk
aXJlY3RvcnkgKyBzdHJGaWxlU2VwYXJhdG9yICsgZGlyX2xpc3RbaV07CiAgICB9CiAgICBudW1G
aWxlcysrOwogIH0KfQpjdXJyX2ZpbGUgPSBudWxsOwoKaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIo
Im51bUZpbGVzIiwgSW50ZWdlci50b1N0cmluZyhudW1GaWxlcykpOwppZGNQaXBlbGluZS5pbnNl
cnRBZnRlcigiZmlsZUxpc3QiLCBmaWxlTGlzdCk7CmlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJm
aWxlTGlzdF9mdWxscGF0aG5hbWVzIiwgZmlsZUxpc3RfZnVsbHBhdGhuYW1lcyk7CmlkY1BpcGVs
aW5lLmRlc3Ryb3koKTsK</value>
</Values>
