<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">streamToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] object:0:required stream</value>
    <value>[i] field:0:required append {"true","false"}</value>
    <value>[o] field:0:required fullpath</value>
    <value>[o] field:0:required length</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklucHV0U3RyZWFtIGlu
c3RyZWFtID0gbnVsbDsKU3RyaW5nIHN0ckZpbGVuYW1lID0gbnVsbDsKbG9uZyBsZW4gPSAwOyAv
LyBmaWxlIGxlbmd0aAppZiAoY3Vyc29yLmZpcnN0KCJzdHJlYW0iKSkKewogIGluc3RyZWFtID0g
KElucHV0U3RyZWFtKSBjdXJzb3IuZ2V0VmFsdWUoKTsKfQplbHNlCnsKICB0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbigiSW5wdXQgcGFyYW1ldGVyIFwnc3RyZWFtXCcgd2FzIG5vdCBmb3VuZC4i
KTsKfQoKaWYgKGN1cnNvci5maXJzdCgiZmlsZW5hbWUiKSkKewogIHN0ckZpbGVuYW1lID0gKFN0
cmluZykgY3Vyc29yLmdldFZhbHVlKCk7Cn0KZWxzZQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIklucHV0IHBhcmFtZXRlciBcJ2ZpbGVuYW1lXCcgd2FzIG5vdCBmb3VuZC4iKTsKfQpi
b29sZWFuIGEgPSBjdXJzb3IuZmlyc3QoImFwcGVuZCIpID8gQm9vbGVhbi52YWx1ZU9mKChTdHJp
bmcpIGN1cnNvci5nZXRWYWx1ZSgpKS5ib29sZWFuVmFsdWUoKSA6IGZhbHNlOwpjdXJzb3IuZGVz
dHJveSgpOwoKLy8gKioqIENoZWNrIGlmIHBhdGggaXMgb24gdGhlIGFsbG93ZWQgbGlzdCAqKioK
dHJ5CnsKICBpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHN0ckZpbGVuYW1lLCAid3JpdGUiKSkKICB7
CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVkIHBhdGggaXMgbm90IG9u
IHRoZSB3cml0ZSBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3VyYXRpb24g
ZmlsZSEiKTsKICB9Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9Ci8vICoqKiBFbmQgY2hlY2sgKioqCgpGaWxlIGZp
bGUgPSBuZXcgRmlsZShzdHJGaWxlbmFtZSk7ClN0cmluZyBiYXNlbmFtZSA9IGZpbGUuZ2V0TmFt
ZSgpOwpGaWxlIGRvdCA9IG51bGw7CnRyeQp7CiAgZG90ID0gZmlsZS5nZXRDYW5vbmljYWxGaWxl
KCkuZ2V0UGFyZW50RmlsZSgpOwp9CmNhdGNoIChJT0V4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9CkZpbGUgdGFyZ2V0RGlyID0gZG90
OyAvLyBuYW1lbHkgJy4nIGRpcmVjdG9yeQoKaWYgKCF0YXJnZXREaXIuZXhpc3RzKCkpCnsKICB0
YXJnZXREaXIubWtkaXJzKCk7Cn0KZmlsZSA9IG5ldyBGaWxlKHRhcmdldERpciwgYmFzZW5hbWUp
OwoKU3RyaW5nIHBhcmVudERpciA9IG51bGw7ClN0cmluZyBkb3REaXIgPSBudWxsOwpTdHJpbmcg
cGF0aCA9IG51bGw7CgpGaWxlIHBhcmVudCA9IHRhcmdldERpci5nZXRQYXJlbnRGaWxlKCk7CkZp
bGVPdXRwdXRTdHJlYW0gZm9zID0gbnVsbDsKQnVmZmVyZWRPdXRwdXRTdHJlYW0gYm9zID0gbnVs
bDsKdHJ5CnsKICBwYXJlbnREaXIgPSBwYXJlbnQuZ2V0Q2Fub25pY2FsUGF0aCgpOwogIGRvdERp
ciA9IHRhcmdldERpci5nZXRDYW5vbmljYWxQYXRoKCk7CiAgcGF0aCA9IGZpbGUuZ2V0Q2Fub25p
Y2FsUGF0aCgpOwogIGZvcyA9IG5ldyBGaWxlT3V0cHV0U3RyZWFtKHBhdGgsIGEpOwogIGludCBC
VUZTSVpFID0gNDA5NjsKICBib3MgPSBuZXcgQnVmZmVyZWRPdXRwdXRTdHJlYW0oZm9zLCBCVUZT
SVpFKTsKCiAgYnl0ZVtdIGJ1ZiA9IG5ldyBieXRlW0JVRlNJWkVdOwogIC8vIFBvc3NpYmxlIHZh
bHVlcyBvZiByOiAoMSkgciA+IDAsIG9yICgyKSByIDwgMCB3aGVuIGVvZiBpcyByZWFjaGVkOyBu
byByCiAgLy8gPSAwLgogIGludCByID0gaW5zdHJlYW0ucmVhZChidWYsIDAsIEJVRlNJWkUpOwog
IHdoaWxlIChyID4gMCkKICB7CiAgICBib3Mud3JpdGUoYnVmLCAwLCByKTsKICAgIGxlbiArPSBy
OwogICAgciA9IGluc3RyZWFtLnJlYWQoYnVmLCAwLCBCVUZTSVpFKTsKICB9CiAgYm9zLmNsb3Nl
KCk7CiAgaW5zdHJlYW0uY2xvc2UoKTsgLy8gcmVhY2hlZCB0aGUgZW5kLW9mLWZpbGUKfQpjYXRj
aCAoSU9FeGNlcHRpb24gZSkKewogIHRyeQogIHsKICAgIGlmIChib3MgIT0gbnVsbCkKICAgIHsK
ICAgICAgYm9zLmNsb3NlKCk7CiAgICB9CiAgICBlbHNlCiAgICB7CiAgICAgIGlmIChmb3MgIT0g
bnVsbCkKICAgICAgewogICAgICAgIGZvcy5jbG9zZSgpOwogICAgICB9CiAgICB9CiAgICBpbnN0
cmVhbS5jbG9zZSgpOwogIH0KICBjYXRjaCAoSU9FeGNlcHRpb24gZTIpCiAgewogICAgdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oZTIpOwogIH0KICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bihlKTsKfQoKY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CmN1cnNvci5sYXN0KCk7CmN1
cnNvci5pbnNlcnRBZnRlcigiZnVsbHBhdGgiLCAiIiArIHBhdGgpOyAvLyBjYW5vbmljYWwgcGF0
aApjdXJzb3IuaW5zZXJ0QWZ0ZXIoImxlbmd0aCIsICIiICsgbGVuKTsKY3Vyc29yLmRlc3Ryb3ko
KTsK</value>
</Values>
