<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">readPropertiesFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[o] object:0:required property</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBz
dHJGaWxlbmFtZSA9IG51bGw7CmlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkKewog
IHN0ckZpbGVuYW1lID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQplbHNlCnsK
ICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291bGQgbm90IHJlYWQgUHJvcGVydGllcyBm
aWxlLiAgZmlsZW5hbWUgaXMgbnVsbCEiKTsKfQoKdHJ5CnsKICBGaWxlIGZpbGUgPSBuZXcgRmls
ZShzdHJGaWxlbmFtZSk7CiAgaWYgKGZpbGUuY2FuUmVhZCgpKQogIHsKICAgIFByb3BlcnRpZXMg
cHJvcGVydHkgPSBuZXcgUHJvcGVydGllcygpOwogICAgSW5wdXRTdHJlYW0gc3RyZWFtID0gbmV3
IGphdmEuaW8uQnVmZmVyZWRJbnB1dFN0cmVhbShuZXcgamF2YS5pby5GaWxlSW5wdXRTdHJlYW0o
ZmlsZSkpOwoKICAgIHRyeQogICAgewogICAgICBwcm9wZXJ0eS5sb2FkKHN0cmVhbSk7CiAgICB9
CiAgICBmaW5hbGx5CiAgICB7CiAgICAgIHN0cmVhbS5jbG9zZSgpOwogICAgfQoKICAgIAogICAg
RW51bWVyYXRpb24gZW51bWVyYXRpb24gPSBwcm9wZXJ0eS5wcm9wZXJ0eU5hbWVzKCk7CiAgICB3
aGlsZSAoZW51bWVyYXRpb24uaGFzTW9yZUVsZW1lbnRzKCkpCiAgICB7CiAgICAgIFN0cmluZyBz
dHJQcm9wZXJ0eU5hbWUgPSAoU3RyaW5nKWVudW1lcmF0aW9uLm5leHRFbGVtZW50KCk7CiAgICAg
IFN0cmluZyBzdHJQcm9wZXJ0eVZhbHVlID0gKFN0cmluZykgcHJvcGVydHkuZ2V0UHJvcGVydHko
c3RyUHJvcGVydHlOYW1lKTsKICAgICAgaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoc3RyUHJvcGVy
dHlOYW1lLCBzdHJQcm9wZXJ0eVZhbHVlKTsKICAgIH0KCiAgICAvLyBQdXQgZW50aXJlIHByb3Bl
cnR5IG9iamVjdCBpbnRvIHRoZSBvdXRwdXQgcGlwZWxpbmUKICAgIGlkY1BpcGVsaW5lLmluc2Vy
dEFmdGVyKCJwcm9wZXJ0eSIsIHByb3BlcnR5KTsKICB9CiAgZWxzZQogIHsKICAgIHRocm93IG5l
dyBTZXJ2aWNlRXhjZXB0aW9uKCJDb3VsZCBub3QgcmVhZCBwcm9wZXJ0aWVzIGZpbGU6ICIgKyBz
dHJGaWxlbmFtZSk7CiAgfQp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKCJFcnJvciByZWFkaW5nIHByb3BlcnRpZXMgZmlsZTogIiArIGUpOwp9CmZp
bmFsbHkKewogIGlkY1BpcGVsaW5lLmRlc3Ryb3koKTsKfQoK</value>
</Values>
