<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">spawnThread</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required serviceName</value>
    <value>[i] record:0:required input</value>
    <value>[o] object:0:required threadHandle</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CklEYXRhIGlu
cHV0ID0gbnVsbDsKU3RyaW5nIHNlcnZpY2VOYW1lID0gbnVsbDsKaWYgKGlkY1BpcGVsaW5lLmZp
cnN0KCJzZXJ2aWNlTmFtZSIpKQp7CiAgc2VydmljZU5hbWUgPSAoU3RyaW5nKSBpZGNQaXBlbGlu
ZS5nZXRWYWx1ZSgpOwp9CmVsc2UKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJzZXJ2
aWNlIGNhbm5vdCBiZSBudWxsIik7Cn0KCmlmIChpZGNQaXBlbGluZS5maXJzdCgiaW5wdXQiKSkK
ewogIGlucHV0ID0gKElEYXRhKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CgovLyAqKiogQ2hl
Y2sgaWYgc2VydmljZSBpcyBvbiB0aGUgYWxsb3dlZCBsaXN0ICoqKgpJRGF0YSBpbiA9IElEYXRh
RmFjdG9yeS5jcmVhdGUoKTsKSURhdGFDdXJzb3IgaWRjSW4gPSBpbi5nZXRDdXJzb3IoKTsKaWRj
SW4uaW5zZXJ0QWZ0ZXIoInBhcmFtTmFtZSIsICJhbGxvd2VkU2VydmljZXMiKTsKaWRjSW4uaW5z
ZXJ0QWZ0ZXIoInBhcmFtVmFsdWUiLCBzZXJ2aWNlTmFtZSk7Ck5TTmFtZSBuc0NoZWNrU2Vydmlj
ZU5hbWUgPSBOU05hbWUuY3JlYXRlKCJQU1V0aWxpdGllcy5jb25maWc6Y2hlY2tQYXJhbWV0ZXJW
YWxpZGl0eSIpOwppZGNJbi5kZXN0cm95KCk7CklEYXRhIG91dDsKdHJ5CnsKICBvdXQgPSBTZXJ2
aWNlLmRvSW52b2tlKG5zQ2hlY2tTZXJ2aWNlTmFtZSwgaW4pOwp9CmNhdGNoIChFeGNlcHRpb24g
ZSkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQpJRGF0
YUN1cnNvciBpZGNPdXQgPSBvdXQuZ2V0Q3Vyc29yKCk7ClN0cmluZyBzdHJWYWxpZCA9IG51bGw7
CmlmIChpZGNPdXQuZmlyc3QoInZhbGlkIikpCnsKICBzdHJWYWxpZCA9IChTdHJpbmcpIGlkY091
dC5nZXRWYWx1ZSgpOwp9CmlkY091dC5kZXN0cm95KCk7CgppZiAoc3RyVmFsaWQuZXF1YWxzKCJm
YWxzZSIpKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmllZCBzZXJ2aWNl
IGlzIG5vdCBvbiB0aGUgYWxsb3dlZCBsaXN0IGluIHRoZSBQU1V0aWxpdGllcyBjb25maWd1cmF0
aW9uIGZpbGUhIik7Cn0KLy8gKioqIEVuZCBjaGVjayAqKioKCnRyeQp7CiAgLy8gU3BsaXQgdGhl
IGludGVyZmFjZSBhbmQgc2VydmljZSBmcm9tIHNlcnZpY2VOYW1lCiAgaWYgKHNlcnZpY2VOYW1l
LmluZGV4T2YoIjoiKSA9PSAtMSkKICB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
U2VydmljZSBuYW1lIG11c3QgYmUgaW4gdGhlIGZvcm1hdCA8aW50ZXJmYWNlPjo8c2VydmljZT4i
KTsKICB9CiAgU3RyaW5nIGlmYyA9IHNlcnZpY2VOYW1lLnN1YnN0cmluZygwLCBzZXJ2aWNlTmFt
ZS5pbmRleE9mKCI6IikpOwogIFN0cmluZyBzZXJ2aWNlID0gc2VydmljZU5hbWUuc3Vic3RyaW5n
KHNlcnZpY2VOYW1lLmluZGV4T2YoIjoiKSArIDEsIHNlcnZpY2VOYW1lLmxlbmd0aCgpKTsKCiAg
Ly8gSW52b2tlIHNlcnZpY2UKICBTZXJ2aWNlVGhyZWFkIHRocmVhZEhhbmRsZSA9IFNlcnZpY2Uu
ZG9UaHJlYWRJbnZva2UoaWZjLCBzZXJ2aWNlLCBJRGF0YVV0aWwuZGVlcENsb25lKGlucHV0KSk7
CiAgaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInRocmVhZEhhbmRsZSIsIHRocmVhZEhhbmRsZSk7
Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5n
ZXRNZXNzYWdlKCkpOwp9CmZpbmFsbHkKewogIGlkY1BpcGVsaW5lLmRlc3Ryb3koKTsKfQo=</value>
</Values>
