<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">bytesToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required filename</value>
    <value>[i] object:0:required bytes</value>
    <value>[i] field:0:required append {"true","false"}</value>
    <value>[o] field:0:required fullpath</value>
    <value>[o] field:0:required length</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCmJ5dGVbXSBi
eXRlcyA9IG51bGw7ClN0cmluZyBzdHJGaWxlbmFtZSA9IG51bGw7CgppZiAoaWRjUGlwZWxpbmUu
Zmlyc3QoImJ5dGVzIikpCnsKICBieXRlcyA9IChieXRlW10pIGlkY1BpcGVsaW5lLmdldFZhbHVl
KCk7Cn0KZWxzZQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIklucHV0IHBhcmFtZXRl
ciBcJ2J5dGVzXCcgd2FzIG5vdCBmb3VuZC4iKTsKfQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZp
bGVuYW1lIikpCnsKICBzdHJGaWxlbmFtZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVl
KCk7Cn0KZWxzZQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIklucHV0IHBhcmFtZXRl
ciBcJ2ZpbGVuYW1lXCcgd2FzIG5vdCBmb3VuZC4iKTsKfQpib29sZWFuIGEgPSBpZGNQaXBlbGlu
ZS5maXJzdCgiYXBwZW5kIikgPyBCb29sZWFuLnZhbHVlT2YoKFN0cmluZykgaWRjUGlwZWxpbmUu
Z2V0VmFsdWUoKSkuYm9vbGVhblZhbHVlKCkgOiBmYWxzZTsKCi8vICoqKiBDaGVjayBpZiBwYXRo
IGlzIG9uIHRoZSBhbGxvd2VkIGxpc3QgKioqCnRyeQp7CiAgaWYgKCFjaGVja1BhdGhWYWxpZGl0
eShzdHJGaWxlbmFtZSwgIndyaXRlIikpCiAgewogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIlNwZWNpZmllZCBwYXRoIGlzIG5vdCBvbiB0aGUgd3JpdGUgYWxsb3dlZCBsaXN0IGluIHRo
ZSBQU1V0aWxpdGllcyBjb25maWd1cmF0aW9uIGZpbGUhIik7CiAgfQp9CmNhdGNoIChFeGNlcHRp
b24gZSkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQov
LyAqKiogRW5kIGNoZWNrICoqKgoKRmlsZSBmaWxlID0gbmV3IEZpbGUoc3RyRmlsZW5hbWUpOwpT
dHJpbmcgYmFzZW5hbWUgPSBmaWxlLmdldE5hbWUoKTsKClN0cmluZyBmdWxscGF0aCA9IG51bGw7
CnRyeQp7CiAgRmlsZSBwYXJlbnQgPSBmaWxlLmdldENhbm9uaWNhbEZpbGUoKS5nZXRQYXJlbnRG
aWxlKCk7CiAgRmlsZSB0YXJnZXREaXIgPSBwYXJlbnQ7CgogIGlmICghdGFyZ2V0RGlyLmV4aXN0
cygpKQogIHsKICAgIHRhcmdldERpci5ta2RpcnMoKTsKICB9CiAgZmlsZSA9IG5ldyBGaWxlKHRh
cmdldERpciwgYmFzZW5hbWUpOwogIGZ1bGxwYXRoID0gZmlsZS5nZXRDYW5vbmljYWxQYXRoKCk7
CiAgRmlsZU91dHB1dFN0cmVhbSB3cml0ZXIgPSBuZXcgRmlsZU91dHB1dFN0cmVhbShmaWxlLmdl
dENhbm9uaWNhbFBhdGgoKSwgYSk7IC8vIGFwcGVuZAogICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAvLyBv
cgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAvLyBub3QKICB3cml0ZXIud3JpdGUoYnl0ZXMpOwogIHdy
aXRlci5jbG9zZSgpOwp9CmNhdGNoIChJT0V4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oZSk7Cn0KCmlkY1BpcGVsaW5lLmxhc3QoKTsKaWRjUGlwZWxpbmUuaW5zZXJ0
QWZ0ZXIoImZ1bGxwYXRoIiwgZnVsbHBhdGgpOwppZGNQaXBlbGluZS5pbnNlcnRBZnRlcigibGVu
Z3RoIiwgIiIgKyBieXRlcy5sZW5ndGgpOwppZGNQaXBlbGluZS5kZXN0cm95KCk7Cg==</value>
</Values>
