<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addDoubles</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required number1</value>
    <value>[i] field:0:required number2</value>
    <value>[i] field:0:optional scale</value>
    <value>[o] field:0:required result</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqCiAqIFNlcnZpY2UgcmVwbGFjZXMgcHViLm1hdGg6YWRkRmxvYXRzLCBhcyB0aGF0IHNlcnZp
Y2Ugc3VmZmVycyBmcm9tIGlzc3VlcwogKiB3aXRoIHRoZSBjb3JlIEpWTSdzIGhhbmRsaW5nIG9m
IHRoZSBhZGRpdGlvbiBvZiBmbG9hdGluZy1wb2ludCBudW1iZXJzLgogKiBTZXJ2aWNlIHRha2Vz
IHRocmVlIGlucHV0czogbnVtYmVyMTogVGhlIGZpcnN0IG51bWJlciB0byBiZSBhZGRlZC4gTXVz
dAogKiBiZSBhIGRvdWJsZS4gbnVtYmVyMjogVGhlIHNlY29uZCBudW1iZXIgdG8gYmUgYWRkZWQu
IE11c3QgYmUgYSBkb3VibGUuCiAqIHNjYWxlIChvcHRpb25hbCk6IFRoZSBzY2FsZSBvZiB0aGUg
cmVzdWx0LiBEZWZhdWx0cyB0byA1LgogKiAKICogVGhlICJyZXN1bHQiIHdpbGwgYmUgYSBTdHJp
bmcgdGhhdCBjb250YWlucyBhIGRvdWJsZSB3aXRoIHRoZSBzcGVjaWZpZWQKICogc2NhbGUuCiAq
IAogKiBBbnkgZXJyb3JzIGVuY291bnRlcmVkIHdpbGwgY2F1c2UgYQogKiBjb20ud20uYXBwLmIy
Yi5zZXJ2ZXIuU2VydmljZUV4Y2VwdGlvbiB0byBiZSB0aHJvd24uCiAqIAogKiAqKk5PVEUqKjog
RW1waXJpY2FsIGV2aWRlbmNlIHNob3dzIHRoYXQgcmVzdWx0cyBtYXkgYmVnaW4gdG8gbG9zZSB0
aGVpcgogKiByZWxpYWJpbGl0eSBhdCBsYXJnZXIgc2NhbGVzLiBTY2FsZXMgbG93ZXIgdGhhbiAx
MCBzZWVtIHRvIHdvcmsgZmluZSBpbgogKiBsaW1pdGVkIHRlc3RpbmcuCiAqIAogKi8KCi8vIElu
c3RhbnRpYXRlIGEgY3Vyc29yIGZvciBhY2Nlc3MgdG8gdGhlIHBpcGVsaW5lCklEYXRhQ3Vyc29y
IHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgovLyBDcmVhdGUgYWxsIG91
dHB1dCAmIHdvcmtpbmcgdmFyaWFibGVzClN0cmluZyBudW1iZXIxU3RyaW5nID0gbmV3IFN0cmlu
ZygpOwpkb3VibGUgbnVtYmVyMTsKU3RyaW5nIG51bWJlcjJTdHJpbmcgPSBuZXcgU3RyaW5nKCk7
CmRvdWJsZSBudW1iZXIyOwpTdHJpbmcgcmVzdWx0U3RyaW5nID0gbmV3IFN0cmluZygpOwpkb3Vi
bGUgcmVzdWx0OwpTdHJpbmcgc2NhbGVTdHJpbmcgPSBuZXcgU3RyaW5nKCk7CmludCBzY2FsZTsK
aW50IHdvcmtpbmdTY2FsZTsKQmlnRGVjaW1hbCBiRE51bWJlcjE7CkJpZ0RlY2ltYWwgYkROdW1i
ZXIyOwpCaWdEZWNpbWFsIGJEUmVzdWx0OwoKLy8gSW5wdXQgVmFyaWFibGVzCmlmIChwaXBlbGlu
ZUN1cnNvci5maXJzdCgibnVtYmVyMSIpID09IGZhbHNlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIk5vIHZhbHVlIHdhcyBzcGVjaWZpZWQgZm9yIFwibnVtYmVyMVwiLiIpOwp9Cm51
bWJlcjFTdHJpbmcgPSAoU3RyaW5nKSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp0cnkKewog
IG51bWJlcjEgPSAoRG91YmxlLnZhbHVlT2YobnVtYmVyMVN0cmluZykpLmRvdWJsZVZhbHVlKCk7
Cn0KY2F0Y2ggKE51bWJlckZvcm1hdEV4Y2VwdGlvbiBuZkV4KQp7CiAgdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oIlRoZSBpbnB1dCB2YXJpYWJsZSBcIm51bWJlcjFcIiBtdXN0IGJlIGEgZmxv
YXQgb3IgIiArICJhIGRvdWJsZS4iKTsKfQoKaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0KCJudW1i
ZXIyIikgPT0gZmFsc2UpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiTm8gdmFsdWUg
d2FzIHNwZWNpZmllZCBmb3IgXCJudW1iZXIyXCIuIik7Cn0KbnVtYmVyMlN0cmluZyA9IChTdHJp
bmcpIHBpcGVsaW5lQ3Vyc29yLmdldFZhbHVlKCk7CnRyeQp7CiAgbnVtYmVyMiA9IChEb3VibGUu
dmFsdWVPZihudW1iZXIyU3RyaW5nKSkuZG91YmxlVmFsdWUoKTsKfQpjYXRjaCAoTnVtYmVyRm9y
bWF0RXhjZXB0aW9uIG5mRXgpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVGhlIGlu
cHV0IHZhcmlhYmxlIFwibnVtYmVyMlwiIG11c3QgYmUgYSBmbG9hdCBvciAiICsgImEgZG91Ymxl
LiIpOwp9CgppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoInNjYWxlIikgPT0gZmFsc2UpCnsKICAv
LyBzY2FsZSBpcyBub3QgbWFuZGF0b3J5LiBEZWZhdWx0IHRvIDUuCiAgc2NhbGUgPSA1Owp9CmVs
c2UKewogIHNjYWxlU3RyaW5nID0gKFN0cmluZykgcGlwZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsK
ICB0cnkKICB7CiAgICBzY2FsZSA9IChJbnRlZ2VyLnZhbHVlT2Yoc2NhbGVTdHJpbmcpKS5pbnRW
YWx1ZSgpOwogIH0KICBjYXRjaCAoTnVtYmVyRm9ybWF0RXhjZXB0aW9uIG5mRXgpCiAgewogICAg
dGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlRoZSBpbnB1dCB2YXJpYWJsZSBcInNjYWxlXCIg
bXVzdCBiZSBhbiAiICsgImludGVnZXIuIik7CiAgfQp9CgovLyBDcmVhdGUgdGhlIEJpZ0RlY2lt
YWwgb2JqZWN0cyByZXByZXNlbnRpbmcgdGhlIG51bWJlcnMgdGhhdCB3ZXJlCi8vIHByb3ZpZGVk
LgpiRE51bWJlcjEgPSBuZXcgQmlnRGVjaW1hbChudW1iZXIxKTsKYkROdW1iZXIyID0gbmV3IEJp
Z0RlY2ltYWwobnVtYmVyMik7CgovLyBTZXJ2aWNlIGJvZHkKLyoKICogU2V0IHNjYWxlLiBUaGlz
IGlzIGNyaXRpY2FsLCBhbmQgaXQgaXMgdGhpcyBzdGF0ZW1lbnQgdGhhdCBkZWZlYXRzIHRoZQog
KiBKVk0gYnVnIHdoZXJlIGZsb2F0aW5nLXBvaW50IHJlc3VsdHMgYXJlIHVucHJlZGljdGFibGUu
CiAqLwpiRE51bWJlcjEgPSBiRE51bWJlcjEuc2V0U2NhbGUoc2NhbGUsIEJpZ0RlY2ltYWwuUk9V
TkRfSEFMRl9VUCk7CgovLyBDb21wdXRlIHRoZSAicmVzdWx0Ii4KYkRSZXN1bHQgPSBiRE51bWJl
cjEuYWRkKGJETnVtYmVyMik7CgovKgogKiBTZXQgc2NhbGUuIFRoaXMgaXMgY3JpdGljYWwsIGFu
ZCBpdCBpcyB0aGlzIHN0YXRlbWVudCB0aGF0IGRlZmVhdHMgdGhlCiAqIEpWTSBidWcgd2hlcmUg
ZmxvYXRpbmctcG9pbnQgcmVzdWx0cyBhcmUgdW5wcmVkaWN0YWJsZS4KICovCmJEUmVzdWx0ID0g
YkRSZXN1bHQuc2V0U2NhbGUoc2NhbGUsIEJpZ0RlY2ltYWwuUk9VTkRfSEFMRl9VUCk7CgpyZXN1
bHQgPSBiRFJlc3VsdC5kb3VibGVWYWx1ZSgpOwpyZXN1bHRTdHJpbmcgPSBTdHJpbmcudmFsdWVP
ZihyZXN1bHQpOwoKLy8gUG9wdWxhdGUgc2VydmljZSBvdXRwdXQKaWYgKHBpcGVsaW5lQ3Vyc29y
LmZpcnN0KCJyZXN1bHQiKSkKICBwaXBlbGluZUN1cnNvci5kZWxldGUoKTsKcGlwZWxpbmVDdXJz
b3IuaW5zZXJ0QWZ0ZXIoInJlc3VsdCIsIHJlc3VsdFN0cmluZyk7CnBpcGVsaW5lQ3Vyc29yLmRl
c3Ryb3koKTsK</value>
</Values>
