<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSystemProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:2:required propertyList</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqCiAqIFNlcnZpY2UgaXMgZGVzaWduZWQgdG8gcmV0dXJuIGEgbGlzdCBvZiBhbGwgYXZhaWxh
YmxlIHN5c3RlbSBwcm9wZXJ0aWVzLgogKiAKICovCgpJRGF0YUN1cnNvciBpZGMgPSBwaXBlbGlu
ZS5nZXRDdXJzb3IoKTsKUHJvcGVydGllcyBwcm9wID0gU3lzdGVtLmdldFByb3BlcnRpZXMoKTsK
RW51bWVyYXRpb24gcHJvcEtleUxpc3QgPSBwcm9wLnByb3BlcnR5TmFtZXMoKTsKVmVjdG9yIHBy
b3BWZWMgPSBuZXcgVmVjdG9yKCk7ClZlY3RvciB2YWx1ZVZlYyA9IG5ldyBWZWN0b3IoKTsKCm91
dGVyOiB3aGlsZSAodHJ1ZSkKewogIGlmIChwcm9wS2V5TGlzdC5oYXNNb3JlRWxlbWVudHMoKSA9
PSB0cnVlKQogIHsKICAgIFN0cmluZyBlbGVtZW50TmFtZSA9IChTdHJpbmcpIHByb3BLZXlMaXN0
Lm5leHRFbGVtZW50KCk7CiAgICBTdHJpbmcgZWxlbWVudFZhbHVlID0gU3lzdGVtLmdldFByb3Bl
cnR5KGVsZW1lbnROYW1lLCAiTm8gcHJvcGVydHkgZm91bmQiKTsKICAgIHByb3BWZWMuYWRkRWxl
bWVudChlbGVtZW50TmFtZSk7CiAgICB2YWx1ZVZlYy5hZGRFbGVtZW50KGVsZW1lbnRWYWx1ZSk7
CiAgfQogIGVsc2UKICAgIGJyZWFrIG91dGVyOwp9CgpTdHJpbmdbXSBhbGxQcm9wc0NvbEhlYWRl
cnMgPSB7ICJLZXkiLCAiVmFsdWUiIH07ClRhYmxlIGFsbFByb3BzID0gbmV3IFRhYmxlKGFsbFBy
b3BzQ29sSGVhZGVycyk7CmZvciAoaW50IGkgPSAwOyBpIDwgcHJvcFZlYy5zaXplKCk7IGkrKykK
ewogIFN0cmluZ1tdIGluZGl2aWR1YWxSb3dzID0geyAoU3RyaW5nKSBwcm9wVmVjLmVsZW1lbnRB
dChpKSwgKFN0cmluZykgdmFsdWVWZWMuZWxlbWVudEF0KGkpIH07CiAgYWxsUHJvcHMuYWRkUm93
KGluZGl2aWR1YWxSb3dzKTsKfQoKaWYgKGlkYy5maXJzdCgicHJvcGVydHlMaXN0IikpCiAgaWRj
LmRlbGV0ZSgpOwoKaWRjLmluc2VydEFmdGVyKCJwcm9wZXJ0eUxpc3QiLCBhbGxQcm9wcyk7Cmlk
Yy5kZXN0cm95KCk7Cg==</value>
</Values>
