<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deepCopy</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required originalObject</value>
    <value>[o] object:0:required clonedObject</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CmlmICghaWRj
UGlwZWxpbmUuZmlyc3QoIm9yaWdpbmFsT2JqZWN0IikpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigib3JpZ2luYWxPYmplY3QgaXMgbnVsbCEiKTsKfQpPYmplY3Qgb3JpZ2luYWxPYmpl
Y3QgPSAoT2JqZWN0KSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwpPYmplY3QgY2xvbmVkT2JqZWN0
ID0gbmV3IE9iamVjdCgpOwoKLy8gdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oImJsYWgiICsK
Ly8gKG9yaWdpbmFsT2JqZWN0LmdldENsYXNzKCkpLmlzQXJyYXkoKSk7CgovLyBUaGlzIGNvZGUg
aXMgdGFrZW4gZnJvbQovLyBodHRwOi8vd3d3LmphdmF3b3JsZC5jb20vamF2YXdvcmxkL2phdmF0
aXBzL2p3LWphdmF0aXA3Ni5odG1sCk9iamVjdE91dHB1dFN0cmVhbSBvb3MgPSBudWxsOwpPYmpl
Y3RJbnB1dFN0cmVhbSBvaXMgPSBudWxsOwoKdHJ5CnsKICBCeXRlQXJyYXlPdXRwdXRTdHJlYW0g
Ym9zID0gbmV3IEJ5dGVBcnJheU91dHB1dFN0cmVhbSgpOyAvLyBBCiAgb29zID0gbmV3IE9iamVj
dE91dHB1dFN0cmVhbShib3MpOyAvLyBCCgogIC8vIHNlcmlhbGl6ZSBhbmQgcGFzcyB0aGUgb2Jq
ZWN0CiAgb29zLndyaXRlT2JqZWN0KG9yaWdpbmFsT2JqZWN0KTsgLy8gQwogIG9vcy5mbHVzaCgp
OyAvLyBECgogIEJ5dGVBcnJheUlucHV0U3RyZWFtIGJpbiA9IG5ldyBCeXRlQXJyYXlJbnB1dFN0
cmVhbShib3MudG9CeXRlQXJyYXkoKSk7IC8vIEUKICBvaXMgPSBuZXcgT2JqZWN0SW5wdXRTdHJl
YW0oYmluKTsgLy8gRgoKICAvLyByZXR1cm4gdGhlIG5ldyBvYmplY3QKICBpZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigiY2xvbmVkT2JqZWN0Iiwgb2lzLnJlYWRPYmplY3QoKSk7IC8vIEcKfQpjYXRj
aCAoRXhjZXB0aW9uIGUpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiRXhjZXB0aW9u
IG1ha2luZyBkZWVwIGNvcHkgb2Ygb2JqZWN0OiAiICsgZSk7Cn0KZmluYWxseQp7CiAgdHJ5CiAg
ewogICAgb29zLmNsb3NlKCk7CiAgICBvaXMuY2xvc2UoKTsKICB9CiAgY2F0Y2ggKEV4Y2VwdGlv
biBlKQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJFeGNlcHRpb24gbWFraW5n
IGRlZXAgY29weSBvZiBvYmplY3Q6ICIgKyBlKTsKICB9CiAgaWRjUGlwZWxpbmUuZGVzdHJveSgp
Owp9Cg==</value>
</Values>
