<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">incrementDate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required startingDate</value>
    <value>[i] field:0:required startingDateFormat</value>
    <value>[i] field:0:required endingDateFormat</value>
    <value>[i] field:0:optional addYears</value>
    <value>[i] field:0:optional addMonths</value>
    <value>[i] field:0:optional addDays</value>
    <value>[i] field:0:optional addHours</value>
    <value>[i] field:0:optional addMinutes</value>
    <value>[i] field:0:optional addSeconds</value>
    <value>[o] field:0:required endingDate</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcg
c3RyU3RhcnRpbmdEYXRlID0gbnVsbDsKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJzdGFydGluZ0Rh
dGUiKSkKewogIHN0clN0YXJ0aW5nRGF0ZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVl
KCk7Cn0KZWxzZQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInN0YXJ0aW5nRGF0ZSBt
dXN0IGJlIHN1cHBsaWVkISIpOwp9ClN0cmluZyBzdHJTdGFydGluZ0RhdGVGb3JtYXQgPSBudWxs
OwppZiAoaWRjUGlwZWxpbmUuZmlyc3QoInN0YXJ0aW5nRGF0ZUZvcm1hdCIpKQp7CiAgc3RyU3Rh
cnRpbmdEYXRlRm9ybWF0ID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQplbHNl
CnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigic3RhcnRpbmdEYXRlRm9ybWF0IG11c3Qg
YmUgc3VwcGxpZWQhIik7Cn0KU3RyaW5nIHN0ckVuZGluZ0RhdGVGb3JtYXQgPSBudWxsOwppZiAo
aWRjUGlwZWxpbmUuZmlyc3QoImVuZGluZ0RhdGVGb3JtYXQiKSkKewogIHN0ckVuZGluZ0RhdGVG
b3JtYXQgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CmVsc2UKewogIHRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJlbmRpbmdEYXRlRm9ybWF0IG11c3QgYmUgc3VwcGxpZWQh
Iik7Cn0KClN0cmluZyBzdHJBZGRZZWFycyA9IG51bGw7ClN0cmluZyBzdHJBZGRNb250aHMgPSBu
dWxsOwpTdHJpbmcgc3RyQWRkRGF5cyA9IG51bGw7ClN0cmluZyBzdHJBZGRIb3VycyA9IG51bGw7
ClN0cmluZyBzdHJBZGRNaW51dGVzID0gbnVsbDsKU3RyaW5nIHN0ckFkZFNlY29uZHMgPSBudWxs
OwoKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJhZGRZZWFycyIpKQp7CiAgc3RyQWRkWWVhcnMgPSAo
U3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CmlmIChpZGNQaXBlbGluZS5maXJzdCgi
YWRkTW9udGhzIikpCnsKICBzdHJBZGRNb250aHMgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRW
YWx1ZSgpOwp9CmlmIChpZGNQaXBlbGluZS5maXJzdCgiYWRkRGF5cyIpKQp7CiAgc3RyQWRkRGF5
cyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0KaWYgKGlkY1BpcGVsaW5lLmZp
cnN0KCJhZGRIb3VycyIpKQp7CiAgc3RyQWRkSG91cnMgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5n
ZXRWYWx1ZSgpOwp9CmlmIChpZGNQaXBlbGluZS5maXJzdCgiYWRkTWludXRlcyIpKQp7CiAgc3Ry
QWRkTWludXRlcyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0KaWYgKGlkY1Bp
cGVsaW5lLmZpcnN0KCJhZGRTZWNvbmRzIikpCnsKICBzdHJBZGRTZWNvbmRzID0gKFN0cmluZykg
aWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQoKU2ltcGxlRGF0ZUZvcm1hdCBzc2RmID0gbmV3IFNp
bXBsZURhdGVGb3JtYXQoc3RyU3RhcnRpbmdEYXRlRm9ybWF0KTsKCkRhdGUgc3RhcnRpbmdEYXRl
ID0gbnVsbDsKdHJ5CnsKICBzdGFydGluZ0RhdGUgPSBzc2RmLnBhcnNlKHN0clN0YXJ0aW5nRGF0
ZSk7Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24o
ZS50b1N0cmluZygpKTsKfQoKR3JlZ29yaWFuQ2FsZW5kYXIgZ2MgPSBuZXcgR3JlZ29yaWFuQ2Fs
ZW5kYXIoKTsKZ2Muc2V0VGltZShzdGFydGluZ0RhdGUpOwoKaWYgKHN0ckFkZFllYXJzICE9IG51
bGwpCnsKICBnYy5hZGQoQ2FsZW5kYXIuWUVBUiwgSW50ZWdlci5wYXJzZUludChzdHJBZGRZZWFy
cykpOwp9CmlmIChzdHJBZGRNb250aHMgIT0gbnVsbCkKewogIGdjLmFkZChDYWxlbmRhci5NT05U
SCwgSW50ZWdlci5wYXJzZUludChzdHJBZGRNb250aHMpKTsKfQppZiAoc3RyQWRkRGF5cyAhPSBu
dWxsKQp7CiAgZ2MuYWRkKENhbGVuZGFyLkRBWV9PRl9NT05USCwgSW50ZWdlci5wYXJzZUludChz
dHJBZGREYXlzKSk7Cn0KaWYgKHN0ckFkZEhvdXJzICE9IG51bGwpCnsKICBnYy5hZGQoQ2FsZW5k
YXIuSE9VUl9PRl9EQVksIEludGVnZXIucGFyc2VJbnQoc3RyQWRkSG91cnMpKTsKfQppZiAoc3Ry
QWRkTWludXRlcyAhPSBudWxsKQp7CiAgZ2MuYWRkKENhbGVuZGFyLk1JTlVURSwgSW50ZWdlci5w
YXJzZUludChzdHJBZGRNaW51dGVzKSk7Cn0KaWYgKHN0ckFkZFNlY29uZHMgIT0gbnVsbCkKewog
IGdjLmFkZChDYWxlbmRhci5TRUNPTkQsIEludGVnZXIucGFyc2VJbnQoc3RyQWRkU2Vjb25kcykp
Owp9CgpEYXRlIGVuZGluZ0RhdGUgPSBnYy5nZXRUaW1lKCk7ClNpbXBsZURhdGVGb3JtYXQgZXNk
ZiA9IG5ldyBTaW1wbGVEYXRlRm9ybWF0KHN0ckVuZGluZ0RhdGVGb3JtYXQpOwpTdHJpbmcgc3Ry
RW5kaW5nRGF0ZSA9IGVzZGYuZm9ybWF0KGVuZGluZ0RhdGUpOwoKaWRjUGlwZWxpbmUuaW5zZXJ0
QWZ0ZXIoImVuZGluZ0RhdGUiLCBzdHJFbmRpbmdEYXRlKTsKaWRjUGlwZWxpbmUuZGVzdHJveSgp
Owo=</value>
</Values>
