<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">writeToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required userData</value>
    <value>[i] field:0:required filename</value>
    <value>[i] field:0:required appendOverwriteFlag</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8geyJhcHBlbmQiLCJvdmVyd3JpdGUiLCJmYWlsSWZGaWxlRXhpc3RzIn0KLy8gQmFzZWQgb24g
UnlhbidzIHdyaXRlRmlsZSBzZXJ2aWNlCgpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOwpTdHJpbmcgc3RyVXNlckRhdGEgPSBudWxsOwpTdHJpbmcgc3RyRnVs
bEZpbGVuYW1lID0gbnVsbDsKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJ1c2VyRGF0YSIpKQp7CiAg
c3RyVXNlckRhdGEgPSAoU3RyaW5nKSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwp9CmlmIChpZGNQ
aXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkKewogIHN0ckZ1bGxGaWxlbmFtZSA9IChTdHJpbmcp
IGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0KZWxzZQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oImZpbGVuYW1lIGlzIG51bGwhIik7Cn0KaWRjUGlwZWxpbmUuZmlyc3QoImFwcGVuZE92
ZXJ3cml0ZUZsYWciKTsKU3RyaW5nIGFwcGVuZE92ZXJ3cml0ZUZsYWcgPSAoU3RyaW5nKSBpZGNQ
aXBlbGluZS5nZXRWYWx1ZSgpOwoKLy8gKioqIENoZWNrIGlmIHBhdGggaXMgb24gdGhlIGFsbG93
ZWQgbGlzdCAqKioKdHJ5CnsKICBpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHN0ckZ1bGxGaWxlbmFt
ZSwgIndyaXRlIikpCiAgewogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmll
ZCBwYXRoIGlzIG5vdCBvbiB0aGUgd3JpdGUgYWxsb3dlZCBsaXN0IGluIHRoZSBQU1V0aWxpdGll
cyBjb25maWd1cmF0aW9uIGZpbGUhIik7CiAgfQp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQovLyAqKiogRW5kIGNo
ZWNrICoqKgoKLy8gU2VwYXJhdGUgZmlsZW5hbWUgaW50byBwYXRoIGFuZCBmaWxlbmFtZQovLyBU
aGlzIGlzIGRvbmUgc28gdGhhdCB0aGUgZGlyZWN0b3J5IGNhbiBiZSB3cml0dGVuIChpZiBuZWNl
c3NhcnkpClN0cmluZyBzZXBhcmF0b3IgPSBTeXN0ZW0uZ2V0UHJvcGVydHkoImZpbGUuc2VwYXJh
dG9yIik7CmludCBpbmRleFNlcGFyYXRvciA9IHN0ckZ1bGxGaWxlbmFtZS5sYXN0SW5kZXhPZihz
ZXBhcmF0b3IpOwppZiAoaW5kZXhTZXBhcmF0b3IgPT0gLTEpCnsKICAvLyBBY2NvdW50IGZvciBm
YWN0IHRoYXQgeW91IGNhbiB1c2UgZWl0aGVyICdcJyBvciAnLycgaW4gV2luZG93cwogIGluZGV4
U2VwYXJhdG9yID0gc3RyRnVsbEZpbGVuYW1lLmxhc3RJbmRleE9mKCcvJyk7Cn0KU3RyaW5nIHN0
clBhdGhOYW1lID0gc3RyRnVsbEZpbGVuYW1lLnN1YnN0cmluZygwLCBpbmRleFNlcGFyYXRvciAr
IDEpOwpTdHJpbmcgc3RyRmlsZU5hbWUgPSBzdHJGdWxsRmlsZW5hbWUuc3Vic3RyaW5nKGluZGV4
U2VwYXJhdG9yICsgMSk7CgpGaWxlV3JpdGVyIGZ3ID0gbnVsbDsKdHJ5CnsKICBGaWxlIHBhdGhU
b0JlV3JpdHRlbiA9IG5ldyBGaWxlKHN0clBhdGhOYW1lKTsKICAvLyBTeXN0ZW0ub3V0LnByaW50
bG4oImNhbm9uaWNhbCBwYXRoID0gIiArCiAgLy8gcGF0aFRvQmVXcml0dGVuLmdldENhbm9uaWNh
bFBhdGgoKSk7CgogIC8vIFdyaXRlIHRoZSBkaXJlY3RvcnkuLi4KICBpZiAocGF0aFRvQmVXcml0
dGVuLmV4aXN0cygpID09IGZhbHNlKQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJQYXRoIGRvZXMgbm90IGV4aXN0ISIpOwogIH0KCiAgLy8gQ2hlY2sgaWYgZmlsZSBleGlzdHMK
ICBGaWxlIGZpbGVUb0JlV3JpdHRlbiA9IG5ldyBGaWxlKHN0ckZ1bGxGaWxlbmFtZSk7CiAgaWYg
KGZpbGVUb0JlV3JpdHRlbi5leGlzdHMoKSA9PSB0cnVlICYmIGFwcGVuZE92ZXJ3cml0ZUZsYWcg
IT0gbnVsbCAmJiBhcHBlbmRPdmVyd3JpdGVGbGFnLmVxdWFscygiZmFpbElmRmlsZUV4aXN0cyIp
KQogIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJGaWxlICIgKyBzdHJGdWxsRmls
ZW5hbWUgKyAiIGFscmVhZHkgZXhpc3RzISIpOwogIH0KCiAgLy8gV3JpdGUgdGhlIGZpbGUuLi4K
ICBpZiAoYXBwZW5kT3ZlcndyaXRlRmxhZyAhPSBudWxsICYmIGFwcGVuZE92ZXJ3cml0ZUZsYWcu
ZXF1YWxzKCJvdmVyd3JpdGUiKSkKICB7CiAgICAvLyBvdmVyd3JpdGUKICAgIGZ3ID0gbmV3IEZp
bGVXcml0ZXIoc3RyRnVsbEZpbGVuYW1lLCBmYWxzZSk7CiAgfQogIGVsc2UKICB7CiAgICAvLyBh
cHBlbmQKICAgIGZ3ID0gbmV3IEZpbGVXcml0ZXIoc3RyRnVsbEZpbGVuYW1lLCB0cnVlKTsKICB9
CiAgZncud3JpdGUoc3RyVXNlckRhdGEpOwp9CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKfQpmaW5hbGx5CnsKICAvLyBD
bG9zZSB0aGUgb3V0cHV0IHN0cmVhbS4uLi4KICB0cnkKICB7CiAgICBmdy5jbG9zZSgpOwogIH0K
ICBjYXRjaCAoRXhjZXB0aW9uIGUpCiAgewogIH0KCiAgaWRjUGlwZWxpbmUuZGVzdHJveSgpOwp9
Cg==</value>
</Values>
