<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">zipFiles2</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:1:required files</value>
    <value>[i] field:0:required output</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZ1tdIGZpbGVzID0g
bnVsbDsKU3RyaW5nIG91dHB1dCA9IG51bGw7ClN0cmluZyBtZXNzYWdlID0gIiI7CmlmIChpZGMu
Zmlyc3QoImZpbGVzIikpCnsKICBmaWxlcyA9IChTdHJpbmdbXSkgaWRjLmdldFZhbHVlKCk7Cn0K
aWYgKGlkYy5maXJzdCgib3V0cHV0IikpCnsKICBvdXRwdXQgPSAoU3RyaW5nKSBpZGMuZ2V0VmFs
dWUoKTsKfQppZGMuZGVzdHJveSgpOwoKLy8gKioqIENoZWNrIGlmIHBhdGhzIGFyZSBvbiB0aGUg
YWxsb3dlZCBsaXN0ICoqKgp0cnkKewogIGZvciAoaW50IGkgPSAwOyBpIDwgZmlsZXMubGVuZ3Ro
OyBpKyspCiAgewogICAgaWYgKCFjaGVja1BhdGhWYWxpZGl0eShmaWxlc1tpXSwgInJlYWQiKSkK
ICAgIHsKICAgICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNpZmllZCBwYXRoIGlz
IG5vdCBvbiB0aGUgcmVhZCBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVzIGNvbmZpZ3Vy
YXRpb24gZmlsZSEiKTsKICAgIH0KICB9CgogIGlmICghY2hlY2tQYXRoVmFsaWRpdHkob3V0cHV0
LCAid3JpdGUiKSkKICB7CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3BlY2lmaWVk
IHBhdGggaXMgbm90IG9uIHRoZSB3cml0ZSBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0aWVz
IGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsKICB9Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhy
b3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9Ci8vICoqKiBFbmQgY2hl
Y2sgKioqCgp0cnkKewogIFppcE91dHB1dFN0cmVhbSB6b3MgPSBuZXcgWmlwT3V0cHV0U3RyZWFt
KG5ldyBGaWxlT3V0cHV0U3RyZWFtKG91dHB1dCkpOwogIGZvciAoaW50IGkgPSAwOyBpIDwgZmls
ZXMubGVuZ3RoOyBpKyspCiAgewogICAgU3lzdGVtLm91dC5wcmludGxuKCJOb3cgYWRkaW5nICIg
KyBmaWxlc1tpXSk7CgogICAgem9zLnB1dE5leHRFbnRyeShuZXcgWmlwRW50cnkoZmlsZXNbaV0p
KTsKICAgIHRyeQogICAgewogICAgICBGaWxlSW5wdXRTdHJlYW0gZmlzID0gbmV3IEZpbGVJbnB1
dFN0cmVhbShmaWxlc1tpXSk7CiAgICAgIGJ5dGVbXSBiID0gbmV3IGJ5dGVbNjU1MzZdOwogICAg
ICBpbnQgYnl0ZVJlYWQgPSAwOwogICAgICB3aGlsZSAoKGJ5dGVSZWFkID0gZmlzLnJlYWQoYikp
ICE9IC0xKQogICAgICB7IC8vIFRpbGwgbm90IGVuZCBvZiBmaWxlCiAgICAgICAgem9zLndyaXRl
KGIsIDAsIGJ5dGVSZWFkKTsKICAgICAgfQogICAgICBmaXMuY2xvc2UoKTsKICAgIH0KICAgIGNh
dGNoIChFeGNlcHRpb24gZSkKICAgIHsKICAgICAgbWVzc2FnZSArPSBmaWxlc1tpXSArICIgIjsK
ICAgIH0KICAgIHpvcy5jbG9zZUVudHJ5KCk7CiAgfQogIHpvcy5jbG9zZSgpOwp9CmNhdGNoIChF
eGNlcHRpb24gZSkKewogIGUucHJpbnRTdGFja1RyYWNlKCk7Cn0KCmlmICghbWVzc2FnZS5lcXVh
bHMoIiIpKQp7CiAgSURhdGFDdXJzb3IgaWRjbyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwogIGlk
Yy5pbnNlcnRBZnRlcigibWVzc2FnZSIsICJDYW4gbm90IHppcCAiICsgbWVzc2FnZSk7CiAgaWRj
LmRlc3Ryb3koKTsKfQo=</value>
</Values>
