<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getServerConfigParameters</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:1:required parameters</value>
    <value>[o] record:1:required paramList</value>
    <value>[o] - field:0:required parameter</value>
    <value>[o] - field:0:required paramValue</value>
    <value>[o] field:0:required paramCount</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gZ2xvYmFsIGRlY2xhcmF0aW9ucwpjaGFyW10gY2J1ZiA9IG51bGw7ClN0cmluZyBjZiA9IG51
bGw7ClN0cmluZyBsaW5lID0gbnVsbDsKaW50IGxpbmVDb3VudCA9IDA7ClN0cmluZ0J1ZmZlciBj
ZkNvbnRlbnRzID0gbmV3IFN0cmluZ0J1ZmZlcigpOwpTdHJpbmdbXSBwYXJhbWV0ZXJzID0gbnVs
bDsKSGFzaHRhYmxlIGNmUGFyYW1zID0gbmV3IEhhc2h0YWJsZSgpOwoKLy8gaW5wdXRzCklEYXRh
Q3Vyc29yIHBDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKaWYgKHBDdXJzb3IuZmlyc3Qo
InBhcmFtZXRlcnMiKSkKewogIHBhcmFtZXRlcnMgPSAoU3RyaW5nW10pIHBDdXJzb3IuZ2V0VmFs
dWUoKTsKICBqYXZhLnV0aWwuQXJyYXlzLnNvcnQocGFyYW1ldGVycyk7Cn0KCnRyeQp7CiAgRmls
ZSBjb25maWdEaXIgPSBjb20ud20uYXBwLmIyYi5zZXJ2ZXIuU2VydmVyQVBJLmdldFNlcnZlckNv
bmZpZ0RpcigpOwoKICBGaWxlIGNvbmZpZ0ZpbGUgPSBuZXcgRmlsZShjb25maWdEaXIsICJzZXJ2
ZXIuY25mIik7CiAgRmlsZVJlYWRlciBjZlJlYWRlciA9IG5ldyBGaWxlUmVhZGVyKGNvbmZpZ0Zp
bGUpOwogIEJ1ZmZlcmVkUmVhZGVyIGNmQlJlYWRlciA9IG5ldyBCdWZmZXJlZFJlYWRlcihjZlJl
YWRlcik7CgogIHdoaWxlIChjZkJSZWFkZXIucmVhZHkoKSkKICB7CiAgICBsaW5lID0gY2ZCUmVh
ZGVyLnJlYWRMaW5lKCk7CgogICAgaWYgKGxpbmUgIT0gbnVsbCAmJiAhbGluZS5zdGFydHNXaXRo
KCIjIikpCiAgICB7CiAgICAgIFN0cmluZ1Rva2VuaXplciBzdCA9IG5ldyBTdHJpbmdUb2tlbml6
ZXIobGluZSwgIj0iKTsKCiAgICAgIC8vIGlmIHBhcmFtZXRlcnMgPT0gbnVsbCwgcmV0dXJuIGV2
ZXJ5dGhpbmcKICAgICAgaWYgKHBhcmFtZXRlcnMgPT0gbnVsbCkKICAgICAgewogICAgICAgIGlm
IChzdC5jb3VudFRva2VucygpID09IDIpCiAgICAgICAgewogICAgICAgICAgY2ZQYXJhbXMucHV0
KHN0Lm5leHRUb2tlbigpLCBzdC5uZXh0VG9rZW4oKSk7CiAgICAgICAgfQogICAgICAgIGVsc2UK
ICAgICAgICB7CiAgICAgICAgICBjZlBhcmFtcy5wdXQoc3QubmV4dFRva2VuKCksICIiKTsKICAg
ICAgICB9CgogICAgICAgIC8vIGlmIHBhcmFtZXRlcnMgZXhpc3QsIG9ubHkgcmV0dXJuIHRoZWly
IHZhbHVlcwogICAgICB9CiAgICAgIGVsc2UKICAgICAgewogICAgICAgIFN0cmluZyBteVBhcmFt
ID0gc3QubmV4dFRva2VuKCk7CiAgICAgICAgaWYgKGphdmEudXRpbC5BcnJheXMuYmluYXJ5U2Vh
cmNoKHBhcmFtZXRlcnMsIG15UGFyYW0pID49IDApCiAgICAgICAgewogICAgICAgICAgaWYgKHN0
Lmhhc01vcmVUb2tlbnMoKSkKICAgICAgICAgIHsKICAgICAgICAgICAgY2ZQYXJhbXMucHV0KG15
UGFyYW0sIHN0Lm5leHRUb2tlbigpKTsKICAgICAgICAgIH0KICAgICAgICAgIGVsc2UKICAgICAg
ICAgIHsKICAgICAgICAgICAgY2ZQYXJhbXMucHV0KG15UGFyYW0sICIiKTsKICAgICAgICAgIH0K
ICAgICAgICB9CiAgICAgIH0KICAgICAgbGluZUNvdW50Kys7CiAgICB9CiAgfQoKfQpjYXRjaCAo
RXhjZXB0aW9uIGUpCnsKICBTZXJ2aWNlLnRocm93RXJyb3IoIkVycm9yIGV4dHJhY3RpbmcgcGFy
YW1ldGVycyBmcm9tIHNlcnZlci5jbmYgZmlsZTpcbiIgKyBlLmdldE1lc3NhZ2UoKSk7Cn0KCi8v
IHBhcmFtTGlzdApJRGF0YVtdIHBhcmFtTGlzdCA9IG5ldyBJRGF0YVtjZlBhcmFtcy5zaXplKCld
OwpTdHJpbmdbXSBzb3J0ZWRLZXlzID0gbmV3IFN0cmluZ1tjZlBhcmFtcy5zaXplKCldOwpFbnVt
ZXJhdGlvbiBwYXJhbXMgPSBjZlBhcmFtcy5rZXlzKCk7CgovLyBzb3J0IHBhcmFtZXRlcnMKaW50
IHBhcmFtQ291bnQgPSAwOwp3aGlsZSAocGFyYW1zLmhhc01vcmVFbGVtZW50cygpKQp7CiAgc29y
dGVkS2V5c1twYXJhbUNvdW50XSA9IChTdHJpbmcpIHBhcmFtcy5uZXh0RWxlbWVudCgpOwogIHBh
cmFtQ291bnQrKzsKfQpqYXZhLnV0aWwuQXJyYXlzLnNvcnQoc29ydGVkS2V5cyk7Cgpmb3IgKHBh
cmFtQ291bnQgPSAwOyBwYXJhbUNvdW50IDwgY2ZQYXJhbXMuc2l6ZSgpOyBwYXJhbUNvdW50Kysp
CnsKICBTdHJpbmcga2V5ID0gc29ydGVkS2V5c1twYXJhbUNvdW50XTsKICBwYXJhbUxpc3RbcGFy
YW1Db3VudF0gPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CiAgSURhdGFDdXJzb3IgcGFyYW1MaXN0
Q3Vyc29yID0gcGFyYW1MaXN0W3BhcmFtQ291bnRdLmdldEN1cnNvcigpOwogIHBhcmFtTGlzdEN1
cnNvci5sYXN0KCk7CiAgcGFyYW1MaXN0Q3Vyc29yLmluc2VydEFmdGVyKCJwYXJhbWV0ZXIiLCBr
ZXkpOwogIHBhcmFtTGlzdEN1cnNvci5sYXN0KCk7CiAgcGFyYW1MaXN0Q3Vyc29yLmluc2VydEFm
dGVyKCJwYXJhbVZhbHVlIiwgKFN0cmluZykgY2ZQYXJhbXMuZ2V0KGtleSkpOwogIHBhcmFtTGlz
dEN1cnNvci5kZXN0cm95KCk7Cn0KCi8vIGphdmEudXRpbC5BcnJheXMuc29ydChwYXJhbUxpc3Qp
OwoKLy8gcGlwZWxpbmUKcEN1cnNvci5sYXN0KCk7CnBDdXJzb3IuaW5zZXJ0QWZ0ZXIoInBhcmFt
TGlzdCIsIHBhcmFtTGlzdCk7CnBDdXJzb3IuaW5zZXJ0QWZ0ZXIoInBhcmFtQ291bnQiLCBqYXZh
LmxhbmcuSW50ZWdlci50b1N0cmluZyhwYXJhbUNvdW50KSk7CnBDdXJzb3IuZGVzdHJveSgpOwo=
</value>
</Values>
