<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invoke</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required folder</value>
    <value>[i] field:0:required service</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBz
dHJTZXJ2aWNlTmFtZSA9IG51bGw7ClN0cmluZyBzdHJGb2xkZXJOYW1lID0gbnVsbDsKdHJ5CnsK
ICBpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInNlcnZpY2UiKSkKICB7CiAgICBzdHJTZXJ2aWNlTmFt
ZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7CiAgfQogIGVsc2UKICB7CiAgICB0
aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBzZXJ2aWNlIG5hbWUiKTsKICB9Cgog
IGlmIChpZGNQaXBlbGluZS5maXJzdCgiZm9sZGVyIikpCiAgewogICAgc3RyRm9sZGVyTmFtZSA9
IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7CiAgfQogIGVsc2UKICB7CiAgICB0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBmb2xkZXIgbmFtZSIpOwogIH0KCiAgaWYg
KHN0clNlcnZpY2VOYW1lLmxlbmd0aCgpID09IDAgfHwgc3RyRm9sZGVyTmFtZS5sZW5ndGgoKSA9
PSAwKQogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkludmFsaWQgc2VydmljZSBuYW1l
Iik7CgogIFN0cmluZyBzdHJGdWxsU2VydmljZU5hbWUgPSBzdHJGb2xkZXJOYW1lICsgIjoiICsg
c3RyU2VydmljZU5hbWU7CgogIC8vICoqKiBDaGVjayBpZiBzZXJ2aWNlIGlzIG9uIHRoZSBhbGxv
d2VkIGxpc3QgKioqCiAgSURhdGEgaW4gPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CiAgSURhdGFD
dXJzb3IgaWRjSW4gPSBpbi5nZXRDdXJzb3IoKTsKICBpZGNJbi5pbnNlcnRBZnRlcigicGFyYW1O
YW1lIiwgImFsbG93ZWRTZXJ2aWNlcyIpOwogIGlkY0luLmluc2VydEFmdGVyKCJwYXJhbVZhbHVl
Iiwgc3RyRnVsbFNlcnZpY2VOYW1lKTsKICBOU05hbWUgbnNDaGVja1NlcnZpY2VOYW1lID0gTlNO
YW1lLmNyZWF0ZSgiUFNVdGlsaXRpZXMuY29uZmlnOmNoZWNrUGFyYW1ldGVyVmFsaWRpdHkiKTsK
ICBpZGNJbi5kZXN0cm95KCk7CiAgSURhdGEgb3V0OwogIG91dCA9IFNlcnZpY2UuZG9JbnZva2Uo
bnNDaGVja1NlcnZpY2VOYW1lLCBpbik7CiAgSURhdGFDdXJzb3IgaWRjT3V0ID0gb3V0LmdldEN1
cnNvcigpOwogIFN0cmluZyBzdHJWYWxpZCA9IG51bGw7CiAgaWYgKGlkY091dC5maXJzdCgidmFs
aWQiKSkKICB7CiAgICBzdHJWYWxpZCA9IChTdHJpbmcpIGlkY091dC5nZXRWYWx1ZSgpOwogIH0K
ICBpZGNPdXQuZGVzdHJveSgpOwoKICBpZiAoc3RyVmFsaWQuZXF1YWxzKCJmYWxzZSIpKQogIHsK
ICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgc2VydmljZSBpcyBub3Qg
b24gdGhlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNVdGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxl
ISIpOwogIH0KICAvLyAqKiogRW5kIGNoZWNrICoqKgoKICBOU05hbWUgbnNOYW1lID0gTlNOYW1l
LmNyZWF0ZShzdHJGdWxsU2VydmljZU5hbWUpOwoKICBJRGF0YSByZXN1bHRzID0gU2VydmljZS5k
b0ludm9rZShuc05hbWUsIHBpcGVsaW5lKTsKICBJRGF0YVV0aWwubWVyZ2UocmVzdWx0cywgcGlw
ZWxpbmUpOwoKfQpjYXRjaCAoRXhjZXB0aW9uIGUpCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbihlLmdldE1lc3NhZ2UoKSk7Cn0KZmluYWxseQp7CiAgaWRjUGlwZWxpbmUuZGVzdHJveSgp
Owp9Cg==</value>
</Values>
