<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">sleep</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required millis</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Cgpsb25nIG1pbGxpcyA9
IDA7CmlmIChjdXJzb3IuZmlyc3QoIm1pbGxpcyIpKQp7CiAgbWlsbGlzID0gTG9uZy5wYXJzZUxv
bmcoKFN0cmluZykgY3Vyc29yLmdldFZhbHVlKCkpOwp9CmVsc2UKewogIHRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKCJJbnB1dCBwYXJhbWV0ZXIgXCdtaWxsaXNcJyB3YXMgbm90IGZvdW5kLiIp
Owp9CmN1cnNvci5kZXN0cm95KCk7CgovLyAqKiogQ2hlY2sgaWYgc2VydmljZSBpcyBvbiB0aGUg
YWxsb3dlZCBsaXN0ICoqKgpJRGF0YSBpbiA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKSURhdGFD
dXJzb3IgaWRjSW4gPSBpbi5nZXRDdXJzb3IoKTsKaWRjSW4uaW5zZXJ0QWZ0ZXIoInBhcmFtTmFt
ZSIsICJtYXhTbGVlcCIpOwpOU05hbWUgbnNDaGVja1NlcnZpY2VOYW1lID0gTlNOYW1lLmNyZWF0
ZSgiUFNVdGlsaXRpZXMuY29uZmlnOmdldFBhcmFtZXRlclZhbHVlIik7CmlkY0luLmRlc3Ryb3ko
KTsKSURhdGEgb3V0Owp0cnkKewogIG91dCA9IFNlcnZpY2UuZG9JbnZva2UobnNDaGVja1NlcnZp
Y2VOYW1lLCBpbik7Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwp9CklEYXRhQ3Vyc29yIGlkY091dCA9IG91dC5nZXRD
dXJzb3IoKTsKU3RyaW5nIHN0clBhcmFtVmFsdWUgPSBudWxsOwppZiAoaWRjT3V0LmZpcnN0KCJw
YXJhbVZhbHVlIikpCnsKICBzdHJQYXJhbVZhbHVlID0gKFN0cmluZykgaWRjT3V0LmdldFZhbHVl
KCk7Cn0KaWRjT3V0LmRlc3Ryb3koKTsKCmlmIChtaWxsaXMgPiBMb25nLnBhcnNlTG9uZyhzdHJQ
YXJhbVZhbHVlKSkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJTcGVjaWZpZWQgc2xl
ZXAgaW50ZXJ2YWwgaGFzIGV4Y2VlZGVkIHRoZSBtYXhpbXVtIGFsbG93ZWQgc2xlZXAgaW50ZXJ2
YWwgIiArIHN0clBhcmFtVmFsdWUgKyAiIHNwZWNpZmllZCBieSB0aGUgUFNVdGlsdGlpZXMgY29u
ZmlndXJhdGlvbiBmaWxlIik7Cn0KLy8gKioqIEVuZCBjaGVjayAqKioKCmlmIChtaWxsaXMgPCAw
KQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlBhcmFtZXRlciBcJ21pbGxpc1wnIG11
c3QgaGF2ZSBhIHBvc2l0aXZlIHZhbHVlLiIpOwp9CnRyeQp7CiAgVGhyZWFkLnNsZWVwKG1pbGxp
cyk7Cn0KY2F0Y2ggKEludGVycnVwdGVkRXhjZXB0aW9uIGUpCnsKfQo=</value>
</Values>
