<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">makeSystemCall</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required command</value>
    <value>[i] field:0:required synchronous {"true","false"}</value>
    <value>[o] field:0:required status</value>
    <value>[o] field:0:required output</value>
    <value>[o] field:0:required error</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ci8vIERPUyBTeW50YXg6IGNtZC5leGUgL2MgJ2NvbW1hbmQnCi8vIEV4YW1wbGU6IGNtZC5leGUg
L2MgY29weSBsb2cudHh0IGxvZzIudHh0CgpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVs
aW5lLmdldEN1cnNvcigpOwpTdHJpbmcgc3RyT3V0cHV0ID0gIiI7ClN0cmluZyBzdHJFcnJvciA9
ICIiOwpTdHJpbmcgc3RyQ29tbWFuZCA9IG51bGw7CmlmIChpZGNQaXBlbGluZS5maXJzdCgiY29t
bWFuZCIpKQp7CiAgc3RyQ29tbWFuZCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7
Cn0KZWxzZQp7CiAgcmV0dXJuOwp9CgovLyAqKiogQ2hlY2sgaWYgY29tbWFuZCBpcyBvbiB0aGUg
YWxsb3dlZCBsaXN0ICoqKgpJRGF0YSBpbiA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKSURhdGFD
dXJzb3IgaWRjSW4gPSBpbi5nZXRDdXJzb3IoKTsKaWRjSW4uaW5zZXJ0QWZ0ZXIoInBhcmFtTmFt
ZSIsICJhbGxvd2VkQ29tbWFuZHMiKTsKaWRjSW4uaW5zZXJ0QWZ0ZXIoInBhcmFtVmFsdWUiLCBz
dHJDb21tYW5kKTsKTlNOYW1lIG5zQ2hlY2tTZXJ2aWNlTmFtZSA9IE5TTmFtZS5jcmVhdGUoIlBT
VXRpbGl0aWVzLmNvbmZpZzpjaGVja1BhcmFtZXRlclZhbGlkaXR5Iik7CmlkY0luLmRlc3Ryb3ko
KTsKSURhdGEgb3V0Owp0cnkKewogIG91dCA9IFNlcnZpY2UuZG9JbnZva2UobnNDaGVja1NlcnZp
Y2VOYW1lLCBpbik7Cn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oZSk7Cn0KSURhdGFDdXJzb3IgaWRjT3V0ID0gb3V0LmdldEN1cnNvcigpOwpTdHJp
bmcgc3RyVmFsaWQgPSBudWxsOwppZiAoaWRjT3V0LmZpcnN0KCJ2YWxpZCIpKQp7CiAgc3RyVmFs
aWQgPSAoU3RyaW5nKSBpZGNPdXQuZ2V0VmFsdWUoKTsKfQppZGNPdXQuZGVzdHJveSgpOwoKaWYg
KHN0clZhbGlkLmVxdWFscygiZmFsc2UiKSkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJTcGVjaWZpZWQgY29tbWFuZCBpcyBub3Qgb24gdGhlIGFsbG93ZWQgbGlzdCBpbiB0aGUgUFNV
dGlsaXRpZXMgY29uZmlndXJhdGlvbiBmaWxlISIpOwp9Ci8vICoqKiBFbmQgY2hlY2sgKioqCgpp
ZGNQaXBlbGluZS5maXJzdCgic3luY2hyb25vdXMiKTsKU3RyaW5nIHN0clN5bmNocm9ub3VzID0g
KFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKClByb2Nlc3MgcHJvY2VzcyA9IG51bGw7
Cgp0cnkKewogIHByb2Nlc3MgPSAoUnVudGltZS5nZXRSdW50aW1lKCkpLmV4ZWMoc3RyQ29tbWFu
ZCk7CgogIGlmIChzdHJTeW5jaHJvbm91cy5lcXVhbHMoInRydWUiKSkKICB7CgogICAgLy8gUHJv
dmlkZSBhbiBvdXRsZXQgZm9yIElPIGZvciB0aGUgcHJvY2VzcwogICAgU3RyaW5nIGxpbmU7CiAg
ICBCdWZmZXJlZFJlYWRlciBpciA9IG5ldyBCdWZmZXJlZFJlYWRlcihuZXcgSW5wdXRTdHJlYW1S
ZWFkZXIocHJvY2Vzcy5nZXRJbnB1dFN0cmVhbSgpKSk7CiAgICBCdWZmZXJlZFJlYWRlciBlciA9
IG5ldyBCdWZmZXJlZFJlYWRlcihuZXcgSW5wdXRTdHJlYW1SZWFkZXIocHJvY2Vzcy5nZXRFcnJv
clN0cmVhbSgpKSk7CiAgICB3aGlsZSAoKGxpbmUgPSBpci5yZWFkTGluZSgpKSAhPSBudWxsKQog
ICAgewogICAgICBTeXN0ZW0ub3V0LnByaW50bG4obGluZSk7CiAgICAgIHN0ck91dHB1dCArPSBs
aW5lICsgJ1xuJzsKICAgIH0KCiAgICB3aGlsZSAoKGxpbmUgPSBlci5yZWFkTGluZSgpKSAhPSBu
dWxsKQogICAgewogICAgICBTeXN0ZW0ub3V0LnByaW50bG4obGluZSk7CiAgICAgIHN0ckVycm9y
ICs9IGxpbmUgKyAnXG4nOwogICAgfQogICAgaXIuY2xvc2UoKTsKICAgIGVyLmNsb3NlKCk7Cgog
ICAgcHJvY2Vzcy53YWl0Rm9yKCk7CgogIH0KCn0KY2F0Y2ggKEV4Y2VwdGlvbiBlKQp7CiAgdGhy
b3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS50b1N0cmluZygpKTsKfQpmaW5hbGx5CnsKICBpZiAo
c3RyU3luY2hyb25vdXMuZXF1YWxzKCJ0cnVlIikgJiYgcHJvY2VzcyAhPSBudWxsKQogIHsKICAg
IGludCBzdGF0dXMgPSBwcm9jZXNzLmV4aXRWYWx1ZSgpOwogICAgaWRjUGlwZWxpbmUuaW5zZXJ0
QWZ0ZXIoInN0YXR1cyIsIEludGVnZXIudG9TdHJpbmcoc3RhdHVzKSk7CiAgfQogIGlkY1BpcGVs
aW5lLmluc2VydEFmdGVyKCJvdXRwdXQiLCBzdHJPdXRwdXQpOwogIGlkY1BpcGVsaW5lLmluc2Vy
dEFmdGVyKCJlcnJvciIsIHN0ckVycm9yKTsKICBwcm9jZXNzLmRlc3Ryb3koKTsKICBpZGNQaXBl
bGluZS5kZXN0cm95KCk7Cn0K</value>
</Values>
