<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">runTContextJob</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required host</value>
    <value>[i] field:0:required port</value>
    <value>[i] field:0:required folder</value>
    <value>[i] field:0:required service</value>
    <value>[i] field:0:required username</value>
    <value>[i] field:0:required password</value>
    <value>[i] field:0:required ttl</value>
    <value>[i] field:0:required retries</value>
    <value>[i] field:0:required useSSL {"false","true"}</value>
    <value>[i] field:0:required privKeyFile</value>
    <value>[i] field:1:required certFiles</value>
    <value>[i] field:0:optional async? {"true","false"}</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCmludCB0dGwg
PSAwOyAvLyBpZiAwIGlzIHVzZWQsIGRlZmF1bHQgdHRsIGlzIHVzZWQKaW50IHJldHJpZXMgPSAw
OwoKU3RyaW5nIGhvc3QgPSAiIjsKU3RyaW5nIHBvcnQgPSAiIjsKU3RyaW5nIGZvbGRlck5hbWUg
PSAiIjsKU3RyaW5nIHNlcnZpY2VOYW1lID0gIiI7CmlmIChpZGNQaXBlbGluZS5maXJzdCgiaG9z
dCIpKQp7CiAgaG9zdCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0KaWYgKGlk
Y1BpcGVsaW5lLmZpcnN0KCJwb3J0IikpCnsKICBwb3J0ID0gKFN0cmluZykgaWRjUGlwZWxpbmUu
Z2V0VmFsdWUoKTsKfQppZiAoaWRjUGlwZWxpbmUuZmlyc3QoImZvbGRlciIpKQp7CiAgZm9sZGVy
TmFtZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cn0KZWxzZQp7CiAgdGhyb3cg
bmV3IFNlcnZpY2VFeGNlcHRpb24oIkZvbGRlciBjYW5ub3QgYmUgbnVsbCEiKTsKfQppZiAoaWRj
UGlwZWxpbmUuZmlyc3QoInNlcnZpY2UiKSkKewogIHNlcnZpY2VOYW1lID0gKFN0cmluZykgaWRj
UGlwZWxpbmUuZ2V0VmFsdWUoKTsKfQplbHNlCnsKICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
bigiU2VydmljZSBjYW5ub3QgYmUgbnVsbCEiKTsKfQoKaWRjUGlwZWxpbmUuZmlyc3QoInVzZXJu
YW1lIik7ClN0cmluZyB1c2VybmFtZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7
CmlkY1BpcGVsaW5lLmZpcnN0KCJwYXNzd29yZCIpOwpTdHJpbmcgcGFzc3dvcmQgPSAoU3RyaW5n
KSBpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoKaWRjUGlwZWxpbmUuZmlyc3QoInVzZVNTTCIpOwpT
dHJpbmcgdXNlU1NMID0gKFN0cmluZykgaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKaWRjUGlwZWxp
bmUuZmlyc3QoInByaXZLZXlGaWxlIik7ClN0cmluZyBwcml2S2V5RmlsZSA9IChTdHJpbmcpIGlk
Y1BpcGVsaW5lLmdldFZhbHVlKCk7ClN0cmluZyBjZXJ0RmlsZXNbXSA9IG51bGw7CmlmIChpZGNQ
aXBlbGluZS5maXJzdCgiY2VydEZpbGVzIikpCiAgY2VydEZpbGVzID0gKFN0cmluZ1tdKSBpZGNQ
aXBlbGluZS5nZXRWYWx1ZSgpOwppZGNQaXBlbGluZS5maXJzdCgiYXN5bmM/Iik7ClN0cmluZyBh
c3luYyA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7CgppZiAoaWRjUGlwZWxpbmUu
Zmlyc3QoInR0bCIpKQp7CiAgU3RyaW5nIFRUTCA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7CiAgdHRsID0gSW50ZWdlci5wYXJzZUludChUVEwpOwp9CmlmIChpZGNQaXBlbGluZS5m
aXJzdCgicmV0cmllcyIpKQp7CiAgU3RyaW5nIFJldHJpZXMgPSAoU3RyaW5nKSBpZGNQaXBlbGlu
ZS5nZXRWYWx1ZSgpOwogIHJldHJpZXMgPSBJbnRlZ2VyLnBhcnNlSW50KFJldHJpZXMpOwp9Cgpp
ZGNQaXBlbGluZS5kZXN0cm95KCk7CgovLyAtLS1Jbml0aWFsaXphdGlvbi0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KdHJ5CnsKICBTdHJpbmcgVVJM
ID0gIiI7CiAgU2VydmVyQVBJIGFwaSA9IG5ldyBTZXJ2ZXJBUEkoKTsKICBpZiAoaG9zdCA9PSBu
dWxsKQogICAgaG9zdCA9IGFwaS5nZXRTZXJ2ZXJOYW1lKCk7CiAgaWYgKHBvcnQgPT0gbnVsbCkK
ICAgIHBvcnQgPSBJbnRlZ2VyLnRvU3RyaW5nKGFwaS5nZXRDdXJyZW50UG9ydCgpKTsKCiAgaWYg
KHBvcnQuZXF1YWxzKCItMSIpKQogICAgVVJMID0gaG9zdDsKICBlbHNlCiAgICBVUkwgPSBob3N0
ICsgIjoiICsgcG9ydDsKCiAgLy8gVENvbnRleHQgaW5pdGlhbGl6YXRpb24KICBUQ29udGV4dCB0
eCA9IG5ldyBUQ29udGV4dCgpOwogIGlmICh1c2VTU0wuZXF1YWxzKCJ0cnVlIikpCiAgewogICAg
dHguc2V0U2VjdXJlKHRydWUpOwogIH0KCiAgaWYgKChwcml2S2V5RmlsZSAhPSBudWxsKSAmJiAo
Y2VydEZpbGVzICE9IG51bGwpKQogIHsKICAgIHR4LnNldFNTTENlcnRpZmljYXRlcyhwcml2S2V5
RmlsZSwgY2VydEZpbGVzKTsKICB9CgogIHR4LmNvbm5lY3QoVVJMLCB1c2VybmFtZSwgcGFzc3dv
cmQpOwoKICAvLyBzdGFydCB0cmFuc2FjdGlvbgogIFN0cmluZyB0aWQgPSB0eC5zdGFydFR4KHR0
bCwgcmV0cmllcyk7CiAgaWYgKGFzeW5jLmVxdWFsc0lnbm9yZUNhc2UoInRydWUiKSkKICB7CiAg
ICB0eC5zdWJtaXRUeCh0aWQsIGZvbGRlck5hbWUsIHNlcnZpY2VOYW1lLCBwaXBlbGluZSk7CiAg
fQogIGVsc2UKICB7CiAgICBJRGF0YSByZXN1bHRzID0gdHguaW52b2tlVHgodGlkLCBmb2xkZXJO
YW1lLCBzZXJ2aWNlTmFtZSwgcGlwZWxpbmUpOwogICAgSURhdGFVdGlsLm1lcmdlKHJlc3VsdHMs
IHBpcGVsaW5lKTsKCiAgfQoKICB0eC5lbmRUeCh0aWQpOwoKICB0eC5kaXNjb25uZWN0KCk7Cgp9
CmNhdGNoIChFeGNlcHRpb24gZSkKewogIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9
Cgo=</value>
</Values>
